-- Data-only OW-05 construction catalogue.  World behaviour comes from the
-- ordinary referenced world-object definitions and their material state.
return {
  {
    id = "construction.timber_wall",
    display_name = "Timber Wall",
    kind = "structural_piece",
    description = "Blocks movement, sight, projectiles and gas. Flammable.",
    world_object_id = "world_object.build.timber_wall",
    costs = { ["resource.material.timber"] = 2 },
  },
  {
    id = "construction.masonry_wall",
    display_name = "Masonry Wall",
    kind = "structural_piece",
    description = "Durable solid cover that blocks movement, sight, projectiles and gas.",
    world_object_id = "world_object.build.masonry_wall",
    costs = { ["resource.material.masonry"] = 3 },
  },
  {
    id = "construction.timber_floor",
    display_name = "Timber Floor",
    kind = "structural_piece",
    description = "Walkable flammable structural floor piece.",
    world_object_id = "world_object.build.timber_floor",
    costs = { ["resource.material.timber"] = 1 },
  },
  {
    id = "construction.metal_floor",
    display_name = "Metal Floor",
    kind = "structural_piece",
    description = "Walkable conductive structural floor piece.",
    world_object_id = "world_object.build.metal_floor",
    costs = { ["resource.material.metal"] = 1 },
  },
  {
    id = "construction.barricade",
    display_name = "Barricade",
    kind = "structural_piece",
    description = "Movable timber cover that blocks movement, sight and projectiles.",
    world_object_id = "world_object.build.barricade",
    costs = { ["resource.material.timber"] = 2, ["resource.material.metal"] = 1 },
  },
  {
    id = "construction.door",
    display_name = "Door",
    kind = "functional_device",
    description = "Manual door. Use it from the faced tile to open or close it.",
    world_object_id = "world_object.build.door",
    costs = { ["resource.material.metal"] = 2, ["resource.material.timber"] = 1 },
  },
  {
    id = "construction.storage_crate",
    display_name = "Storage Crate",
    kind = "functional_device",
    description = "Persistent spatial storage.",
    world_object_id = "world_object.build.storage_crate",
    costs = { ["resource.material.timber"] = 2, ["resource.material.metal"] = 1 },
  },
  {
    id = "construction.generator",
    display_name = "Generator",
    kind = "functional_device",
    description = "Powers the local construction circuit.",
    world_object_id = "world_object.build.generator",
    costs = { ["resource.material.metal"] = 4 },
  },
  {
    id = "construction.breaker",
    display_name = "Breaker",
    kind = "functional_device",
    description = "Controls the local construction circuit.",
    world_object_id = "world_object.build.breaker",
    costs = { ["resource.material.metal"] = 2 },
  },
  {
    id = "construction.reconstruction_station",
    display_name = "Reconstruction Station",
    kind = "functional_device",
    description = "A persistent reconstruction station that can become your anchor.",
    world_object_id = "world_object.station.reconstruction",
    costs = { ["resource.material.metal"] = 6, ["resource.material.masonry"] = 3 },
  },
}
