return {
  { id = "charm.legacy.iron_heart", display_name = "Iron Heart Charm", description = "+2 maximum HP while equipped.", price = 6, granted_boon_ids = { "boon.legacy.iron_heart" }, render_style = "charm" },
  { id = "charm.legacy.windwalker", display_name = "Windwalker Charm", description = "Dash cooldown -1 while equipped.", price = 5, granted_boon_ids = { "boon.legacy.windwalker" }, render_style = "charm" },
  { id = "charm.legacy.demolition", display_name = "Demolition Charm", description = "Bomb radius +1 while equipped.", price = 5, granted_boon_ids = { "boon.legacy.demolition" }, render_style = "charm" },
  { id = "charm.legacy.flare_lens", display_name = "Flare Lens", description = "Flare light +2 while equipped.", price = 4, granted_boon_ids = { "boon.legacy.flare_lens" }, render_style = "charm" },
  { id = "charm.legacy.quick_reload", display_name = "Quick Reload Charm", description = "On a successful reload, reduce Dash recharge by 1.", price = 5, granted_boon_ids = { "boon.legacy.quick_reload" }, render_style = "charm",
    reactive_effects = { { id = "quick_reload", trigger = "on_reload", description = "On reload, reduce Dash recharge by 1.", effect = { kind = "cooldown_reduction", amount = 1 } } } },
  { id = "charm.legacy.kinetic_capacitor", display_name = "Kinetic Capacitor", description = "Melee force +1 while equipped.", price = 6, granted_boon_ids = { "boon.legacy.kinetic_capacitor" }, render_style = "charm" },
  { id = "charm.legacy.edge_tuning", display_name = "Edge Tuning Charm", description = "Melee damage +1 while equipped.", price = 6, granted_boon_ids = { "boon.legacy.edge_tuning" }, render_style = "charm" },
  { id = "charm.legacy.ballistic_lens", display_name = "Ballistic Lens", description = "Projectile damage +1 while equipped.", price = 7, granted_boon_ids = { "boon.legacy.ballistic_lens" }, render_style = "charm" },
  { id = "charm.legacy.pathfinder", display_name = "Pathfinder Charm", description = "On breaking terrain or an object, reduce Dash recharge by 1. Legacy routes still need one fewer objective.", price = 5, granted_boon_ids = { "boon.legacy.pathfinder" }, render_style = "charm",
    reactive_effects = { { id = "pathfinder", trigger = "on_terrain_break", description = "On breaking terrain or an object, reduce Dash recharge by 1.", effect = { kind = "cooldown_reduction", amount = 1 } } } },
  { id = "charm.legacy.arc_relay", display_name = "Arc Relay", description = "On projectile pierce, arc electricity from the pierced target while Shock Coil is functional.", price = 8, granted_boon_ids = {}, render_style = "charm",
    reactive_effects = { { id = "arc_relay", trigger = "on_pierce", description = "On projectile pierce, arc electricity from the pierced target while Shock Coil is functional.",
      conditions = { attack_tag = "piercing", requires_capability = "ability.electrical.discharge" }, effect = { kind = "chain_electricity", max_cells = 12, damage = 1 } } } },
  { id = "charm.legacy.kinetic_feedback", display_name = "Kinetic Feedback", description = "When your Force causes a structural collision, burst Force from the impact.", price = 8, granted_boon_ids = {}, render_style = "charm",
    reactive_effects = { { id = "kinetic_feedback", trigger = "on_push_collision", description = "When your Force causes a structural collision, burst Force from the impact.",
      conditions = { attack_tag = "forceful" }, effect = { kind = "kinetic_burst", radius = 1, force = 1 } } } },
  { id = "charm.legacy.recycler", display_name = "Recycler", description = "On a ranged kill, load 1 compatible round into the active magazine.", price = 8, granted_boon_ids = {}, render_style = "charm",
    reactive_effects = { { id = "recycler", trigger = "on_kill", description = "On a ranged kill, load 1 compatible round into the active magazine.",
      conditions = { attack_tag = "projectile", requires_ranged = true }, effect = { kind = "magazine_refund", amount = 1 } } } },
  { id = "charm.legacy.rupture_core", display_name = "Rupture Core", description = "When your attack breaks an enemy component, detonate a small blast if Volatile Charge is functional.", price = 9, granted_boon_ids = {}, render_style = "charm",
    reactive_effects = { { id = "rupture_core", trigger = "on_component_break", description = "When your attack breaks an enemy component, detonate a small blast if Volatile Charge is functional.",
      conditions = { requires_capability = "ability.explosive.self_destruct" }, effect = { kind = "small_explosion", radius = 1, damage = 1, force = 1, ignite = true } } } },
}
