local F=require('tests.fixtures')
local W=require('src.world')
local M=require('src.materials')
local U=require('src.util')
local H=require('src.history')
local Cmd=require('src.commands')
local J=require('src.jobs')
local S=require('src.structures')
local Sim=require('src.sim')
local L=require('src.labor')
local Content=require('src.content')
local E=require('src.ecology')
local Blasts=require('src.blasts')
local Metrics=require('src.metrics')
local G=require('src.generate')
local Map=require('src.mapfile')
local Codec=require('src.codec')
local Suite={}
function Suite.run()
 local r={groups=0,assertions=0}
 local function check(v,s)r.assertions=r.assertions+1;assert(v,s or 'Expansion assertion failed')end
 local function eq(a,b,s)check(a==b,(s or 'Mismatch')..': '..tostring(a):sub(1,120)..' vs '..tostring(b):sub(1,120))end
 local function group(name,fn)local ok,e=pcall(fn);assert(ok,name..' FAILED: '..tostring(e));r.groups=r.groups+1;print('PASS  '..name)end
 local function budgets(w)local m=Metrics.measure(w);eq(m.waterResidual,0,'water');eq(m.mineralResidual,0,'mineral');eq(m.foodResidual,0,'food')end
 local function install(w,o)
  o=o or {};o.version=1;o.crew=3;o.flora=o.flora or {};o.fauna=o.fauna or {};o.sites=o.sites or {};o.ruins=o.ruins or {};Content.install(w,o);return w.content
 end
 local function crew(n)
  local w=F.world();for i=1,n do F.worker(w,5+i*3,24,'Worker '..i) end;return w
 end
 group('Whole-worker percentages sum exactly, including an empty pool',function()
  local w=crew(3);local p=L.default(w);p.weights={general=0,dig=50,build=25,haul=25,farm=0,pump=0,field=0}
  for n=0,40 do local q=L.apportion(n,p.weights);local sum=0;for _,v in pairs(q)do sum=sum+v;check(v%1==0)end;eq(sum,n)end
  local q=L.apportion(3,p.weights);eq(q.dig,1);eq(q.build,1);eq(q.haul,1)
  q=L.apportion(6,p.weights);eq(q.dig,3);eq(q.build,2);eq(q.haul,1)
  local weights=p.weights
  for _=1,45 do weights=L.adjust(weights,'farm',5)end;eq(weights.farm,100)
  for _=1,21 do weights=L.adjust(weights,'farm',-5)end;eq(weights.general,100)
 end)
 group('Pinned crew are outside quotas; forbidden duties can leave vacancies',function()
  local w=crew(3);local p=L.default(w);p.quotas=true;p.weights={general=0,dig=50,build=50,haul=0,farm=0,pump=0,field=0};p.people[1].role='farm'
  local a,n=L.allocate(w,p);eq(a[w.workers[1].id],'farm');eq(n.dig+n.build,2)
  p.people[2].prefs.dig=0;p.people[3].prefs.dig=0;a=L.allocate(w,p)
  check(a[w.workers[2].id]=='unfilled' or a[w.workers[3].id]=='unfilled')
  w.workers[3].alive=false;a,n=L.allocate(w,p);eq(n.dig+n.build,1);eq(a[w.workers[3].id],nil)
 end)
 group('Named orders override quotas but never OFF duties',function()
  local w=crew(2);local a,b=w.workers[1],w.workers[2];w.labor=L.default(w);w.labor.people[1].role='farm'
  local j=J.add(w,'dig',7,6);local task={kind='work',job=j.id}
  eq(L.score(w,a,task),nil);j.owner=a.id;check(L.score(w,a,task)~=nil);eq(L.score(w,b,task),nil)
  w.labor.people[1].prefs.dig=0;eq(L.score(w,a,task),nil)
  check(not Cmd.valid(w,{type='labor',plan={}}));local p=L.default(w);p.weights.general=90;check(not Cmd.valid(w,{type='labor',plan=p}))
 end)
 group('Policy updates and job reassignment release resources without duplication',function()
  local w=crew(2);local a,b=w.workers[1],w.workers[2];W.stack(w,'stone',16,12,24);F.baseline(w)
  local j=J.add(w,'build',11,6,'wall',2)
  for _=1,100 do Sim.step(w);if a.carry or b.carry then break end end
  check(a.carry or b.carry,'Fetched actual supplies')
  local p=L.default(w);p.people[1].prefs.build=0;p.people[2].prefs.build=0;L.apply(w,p)
  check(not a.carry and not b.carry);check(not j.assigned);budgets(w)
  Cmd.apply(w,{type='target_order',gx=11,gy=6,worker=a.id});eq(j.owner,a.id)
  Cmd.apply(w,{type='target_order',gx=11,gy=6,worker=0});eq(j.owner,nil)
 end)
 group('Different workers actually execute different named jobs',function()
  local w=F.world();local a=F.worker(w,13,24,'Miner');local b=F.worker(w,18,24,'Builder')
  W.stack(w,'stone',4,16,24);F.fill(w,25,21,28,24,M.ROCK);F.baseline(w)
  check(Cmd.apply(w,{type='order',kind='dig',gx=7,gy=6,worker=a.id,priority=2}))
  check(Cmd.apply(w,{type='order',kind='build',build='ladder',gx=10,gy=6,worker=b.id,priority=2}))
  F.steps(w,450);eq(w.jobs[1].state,'done');eq(w.jobs[2].state,'done');check(w.structures[W.slot(w,10,6)])
  budgets(w)
 end)
 group('Rally holds, reachable paths, release, and hunger overrides work',function()
  local w=crew(1);local a=w.workers[1];W.stack(w,'food',2,10,24);F.baseline(w)
  Cmd.apply(w,{type='rally',worker=a.id,x=40,y=24});F.steps(w,130)
  check(math.abs(a.x-40)<=3,'Rallied near point');check(a.task and a.task.kind=='rally')
  a.hunger=85;F.steps(w,180);check(a.hunger<60,'Food need interrupts holding')
  check(a.directive,'Hold remains an order after eating')
  Cmd.apply(w,{type='releaserally',worker=a.id});eq(a.directive,nil);budgets(w)
 end)
 group('Challenge archive rejects all new command families and preserves its live run',function()
  local w=crew(3);local h=H.new(w);h:advance();h:advance();h:seek(0)
  local ok=h:queue({type='labor',plan=L.default(w)});eq(ok,false)
  ok=h:queue({type='rally',worker=w.workers[1].id,x=30,y=24});eq(ok,false)
  eq(H.fromText(h:saveText()).live.tick,2)
 end)
 group('Charge construction, worker arming and fuse are separate operations',function()
  local w=crew(1);local a=w.workers[1];W.stack(w,'metal',4,11,24);F.baseline(w)
  local j=J.add(w,'build',9,6,'charge',2);F.steps(w,240);eq(j.state,'done')
  local slot=W.slot(w,9,6);local charge=w.structures[slot];check(charge);eq(charge.fuseAt,nil)
  check(not Cmd.valid(w,{type='arm',slot=slot,worker=99999}))
  check(Cmd.apply(w,{type='arm',slot=slot,worker=a.id}))
  F.steps(w,4);eq(charge.fuseAt,nil,'Arming is not instant')
  for _=1,180 do Sim.step(w);if charge.fuseAt then break end end
  check(charge.fuseAt and charge.fuseAt-w.tick==80,'Arming produces a full fuse')
  check(not Cmd.valid(w,{type='arm',slot=slot}),'Cannot reset the fuse');budgets(w)
 end)
 group('Blast wave damages occupants, transforms water and accounts material losses',function()
  local w=crew(1);local a=w.workers[1];a.x,a.y=26,24
  S.install(w,7,6,'charge');W.put(w,29,24,M.WATER);W.put(w,30,24,M.ICE);W.put(w,31,23,M.BEDROCK)
  F.baseline(w);Blasts.detonate(w,W.slot(w,7,6));eq(w.structures[W.slot(w,7,6)],nil)
  check(a.hp<=0,'Blast lethal to nearby crew');eq(W.get(w,31,23),M.BEDROCK)
  eq(W.get(w,29,24),M.STEAM);eq(W.get(w,30,24),M.WATER);check(w.ledger.demolitionWaste>4)
  budgets(w);require('src.colonists').step(w);eq(a.alive,false);eq(a.reason,'blast trauma')
 end)
 group('Charges chain on the following tick and bedrock shields a chamber',function()
  local w=crew(1);S.install(w,7,6,'charge');S.install(w,8,6,'charge')
  F.fill(w,36,3,36,46,M.BEDROCK);W.put(w,38,24,M.ROCK);F.baseline(w)
  w.tick=10;Blasts.detonate(w,W.slot(w,7,6));local second=w.structures[W.slot(w,8,6)]
  check(second and second.fuseAt==11);Blasts.step(w);check(w.structures[W.slot(w,8,6)])
  w.tick=11;Blasts.step(w);eq(w.structures[W.slot(w,8,6)],nil);eq(W.get(w,38,24),M.ROCK);budgets(w)
 end)
 group('Ward uses real water; disabling it removes protection',function()
  local w=crew(1);local ward=S.install(w,4,6,'ward');ward.tank=2;F.baseline(w)
  check(E.warded(w,15,24));ward.enabled=false;check(not E.warded(w,15,24));ward.enabled=true
  w.tick=120;S.step(w);eq(ward.tank,1);w.tick=240;S.step(w);eq(ward.tank,0);check(not E.warded(w,15,24));budgets(w)
 end)
 group('Survey and salvage require reachable workers and preserve finite cache stock',function()
  local w=crew(1);local e=install(w,{sites={{kind='cache',x=23,y=24,stock={metal=9,water=4,food=3},phase=0}}})
  F.baseline(w);local cache=e.sites[1];eq(e.discoveries['sites:cache'],nil)
  Cmd.apply(w,{type='field',kind='survey',target=cache.id});F.steps(w,150)
  check(e.discoveries['sites:cache']);eq(cache.stock.metal,9,'Survey does not loot')
  Cmd.apply(w,{type='field',kind='salvage',target=cache.id});F.steps(w,150)
  eq(cache.alive,false);eq(cache.stock.metal,0);eq(W.totalResource(w,'metal'),9);budgets(w)
 end)
 group('Living interactions change terrain and retain water and food ledgers',function()
  local w=crew(1);w.workers[1].x=7
  local e=install(w,{flora={{kind='filter',x=20,y=24,food=2,water=1,phase=0},{kind='thorn',x=32,y=24,food=5,water=1,phase=0}},fauna={{kind='grazer',x=40,y=24,food=12,phase=0}}})
  W.put(w,19,24,M.STEAM);W.put(w,33,24,M.SAND);F.baseline(w)
  w.tick=20;E.step(w);eq(W.get(w,19,24),M.WATER)
  w.tick=240;E.step(w);eq(W.get(w,33,24),M.ROCK)
  for t=241,1100 do w.tick=t;E.step(w)end
  budgets(w);Content.validate(w)
 end)
 group('Noise wakes sentinels; barriers constrain creatures; bounded reproduction transfers food',function()
  local w=crew(1);local e=install(w,{fauna={{kind='sentinel',x=40,y=24,food=0,phase=0},{kind='grazer',x=22,y=24,food=20,phase=0}}})
  F.fill(w,30,3,31,24,M.BEDROCK);F.baseline(w)
  require('src.signals').emit(w,'mining',42,24,4);w.tick=1;E.step(w);eq(e.fauna[1].awake,true)
  for t=2,800 do w.tick=t;E.step(w)end
  check(e.fauna[1].x>31,'Cannot cross a solid wall');budgets(w)
  for _=1,90 do local c=E.spawn(w,'grazer',10,24,0);if not c then break end end
  check(#e.fauna<=64,'Population cap')
 end)
 group('Nursery salvage transfers stored biomass rather than inventing offspring food',function()
  local w=crew(1);local e=install(w,{sites={{kind='nursery',x=30,y=24,stock={food=8,water=3},phase=0}}})
  F.baseline(w);E.salvage(w,e.sites[1],'sites');eq(e.sites[1].alive,false);check(#e.fauna==1);check(#e.flora==1);budgets(w)
 end)
 group('Cull order pursues a moving creature through normal work scheduling',function()
  local w=crew(1);local e=install(w,{fauna={{kind='grazer',x=15,y=24,food=6,phase=0}}});F.baseline(w)
  local target=e.fauna[1];Cmd.apply(w,{type='field',kind='cull',target=target.id,worker=w.workers[1].id});F.steps(w,300)
  eq(target.alive,false);eq(w.jobs[1].state,'done');budgets(w)
 end)
 group('New layouts and 3/6/9 starts validate and round-trip exact encounters',function()
  local layouts={'karst','labyrinth','roots','chasms','crystal'}
  for i,layout in ipairs(layouts)do
   local n=({3,6,9})[(i-1)%3+1];local w=G.make(777,'frontier','challenge',128,80,{layout=layout,climate='overgrown',crew=n})
   eq(#w.workers,n);require('src.expedition').validateStart(w,w.home,n);W.validate(w)
   local d=Map.fromWorld(w);eq(d.version,2);check(d.features);eq(d.features.crew,n)
   local text=Map.encode(d);local restored=Map.toWorld(Map.decode(text));eq(Map.encode(Map.fromWorld(restored)),text)
   eq(Codec.encode(w.mat),Codec.encode(restored.mat));eq(Codec.encode(Content.template(w)),Codec.encode(Content.template(restored)))
  end
 end)
 group('Legacy baked maps and frontier-v1 recipes remain valid',function()
  local f=assert(io.open('maps/examples/noise-12345.dwmap.json','rb'));local text=f:read('*a');f:close()
  local d=Map.decode(text);eq(d.version,1);local w=Map.toWorld(d);eq(w.content,nil)
  local regenerated=Map.toWorld(Map.regenerate(d,{}));eq(Codec.encode(w.mat),Codec.encode(regenerated.mat),'Legacy material cells');eq(Codec.encode(w.biomes),Codec.encode(regenerated.biomes),'Legacy biome cells')
 end)
 group('Authentic 0.3 frontier saves continue unchanged; new envelopes prevent downgrade',function()
  local f=assert(io.open('tests/data/legacy-v030.dw','rb'));local h=H.fromText(f:read('*a'));f:close()
  local expected=assert(io.open('tests/data/legacy-v030-expected.txt','rb'));local tick=tonumber(expected:read('*l'));local hash=expected:read('*l');expected:close()
  while h.live.tick<tick do h:advance()end
  eq(Codec.hash(h.live),hash);eq(h.live.content,nil)
  eq(Codec.decode(h:saveText()).version,'0.4.0','Old applications must reject the new save envelope')
 end)
 group('External lethal damage cannot be healed into life by a bed',function()
  local w=crew(1);local a=w.workers[1];local bed=S.install(w,3,6,'bed')
  a.task={kind='rest',slot=W.slot(w,3,6),path={},next=1};a.hp=0;a.hunger=0;a.injuryCause='blast trauma'
  require('src.colonists').step(w);eq(a.alive,false);eq(a.hp,0)
 end)
 group('Feature imports reject hostile counts, unknown identities and invalid state',function()
  local w=G.make(12,'frontier','practice',128,80);local d=Map.fromWorld(w)
  local bad=U.deep(d);bad.features.crew=999;check(not pcall(Map.validate,bad))
  bad=U.deep(d);bad.features.fauna={{kind='unknown',x=20,y=20,food=6,phase=0}};check(not pcall(Map.validate,bad))
  bad=U.deep(d);bad.features.sites={{kind='cache',x=20,y=20,stock={food=99999999},phase=0}};check(not pcall(Map.validate,bad))
  bad=U.deep(d);bad.features.lua='os.execute(...)';check(not pcall(Map.validate,bad))
  local a=U.deep(w);a.content.version=2;check(not pcall(W.validate,a))
 end)
 group('Full-history replay includes policies, ecology, fieldwork and charge fuses',function()
  local w=crew(3);local e=install(w,{sites={{kind='cache',x=38,y=24,stock={food=3},phase=0}},flora={{kind='filter',x=44,y=24,food=3,water=2,phase=0}}})
  S.install(w,7,6,'charge');local h=H.new(w);local plan=L.default(w);plan.people[1].role='field'
  check(h:queue({type='labor',plan=plan}));check(h:queue({type='arm',slot=W.slot(w,7,6),worker=w.workers[1].id}))
  for _=1,240 do h:advance()end
  local expected=Codec.encode(h.live);h:seek(110);while h.seekTarget do h:updateSeek(20)end
  h:seek(240);while h.seekTarget do h:updateSeek(20)end;eq(Codec.encode(h.view),expected)
  local restored=H.fromText(h:saveText());eq(Codec.encode(restored.live),expected);budgets(restored.live)
 end)
 print(r.groups..' expansion groups; '..r.assertions..' assertions passed.');return r
end
return Suite
