import type { GameConfig } from '../core/types';
import type { LobbyConfig, RoomSnapshot } from '../net/protocol';
import type { GamePreferences } from '../preferences';
import { escapeHtml } from './markup';

export type HomePanel = 'play' | 'settings';

export interface HomeView {
  panel: HomePanel;
  config: LobbyConfig;
  preferences: GamePreferences;
  playerName: string;
  roomCode: string;
  serverUrl: string;
  connected: boolean;
  notice?: string;
}

const configFields = (config: LobbyConfig, prefix: string) => `<label>campaign seed <input id="${prefix}-seed" maxlength="32" value="${escapeHtml(config.seed)}"></label><div class="home-split"><label>holes <select id="${prefix}-holes">${[3, 6, 9, 18].map((count) => `<option value="${count}" ${config.holeCount === count ? 'selected' : ''}>${count}</option>`).join('')}</select></label><label>player seats <select id="${prefix}-seats">${Array.from({ length: 8 }, (_, index) => index + 1).map((count) => `<option value="${count}" ${config.maxHumans === count ? 'selected' : ''}>${count}</option>`).join('')}</select></label></div><div class="home-split"><label>AI enemies <select id="${prefix}-bots">${Array.from({ length: 5 }, (_, index) => index).map((count) => `<option value="${count}" ${config.botCount === count ? 'selected' : ''}>${count}</option>`).join('')}</select></label><label>AI skill <select id="${prefix}-skill"><option value="adaptive" ${config.botSkill === 'adaptive' ? 'selected' : ''}>adaptive</option>${Array.from({ length: 10 }, (_, index) => index + 1).map((skill) => `<option value="${skill}" ${config.botSkill === skill ? 'selected' : ''}>${skill}</option>`).join('')}</select></label></div>`;

const settingsFields = (preferences: GamePreferences) => `<section class="home-settings panel"><header><p class="eyebrow">PERSISTENT CLIENT SETTINGS</p><h2>settings</h2></header><div class="settings-grid"><label class="setting-toggle"><input data-preference="reducedMotion" type="checkbox" ${preferences.reducedMotion ? 'checked' : ''}> reduced motion and flash</label><label class="setting-toggle"><input data-preference="highContrast" type="checkbox" ${preferences.highContrast ? 'checked' : ''}> high-contrast palette</label><label class="setting-toggle"><input data-preference="controllerVibration" type="checkbox" ${preferences.controllerVibration ? 'checked' : ''}> controller vibration</label><label>master volume <input data-preference-range="masterVolume" type="range" min="0" max="1" step="0.05" value="${preferences.masterVolume}"></label><label>effects volume <input data-preference-range="effectsVolume" type="range" min="0" max="1" step="0.05" value="${preferences.effectsVolume}"></label><label>controller deadzone <input data-preference-range="controllerDeadzone" type="range" min="0.05" max="0.5" step="0.01" value="${preferences.controllerDeadzone}"></label><label>controller aim sensitivity <input data-preference-range="controllerAimSensitivity" type="range" min="0.5" max="2" step="0.05" value="${preferences.controllerAimSensitivity}"></label></div><p class="hint">The standard gamepad layout uses the left stick to aim, A to shoot, B for a held item, and Menu/Start to pause.</p><button data-home-panel="play">back to clubhouse</button></section>`;

export const lobbyConfigFromGame = (config: GameConfig): LobbyConfig => ({ seed: config.seed, holeCount: config.holeCount, botCount: config.botCount, botSkill: config.botSkill, maxHumans: config.humanCount });

export const renderHomeMarkup = (view: HomeView) => `<main class="home-shell"><header class="home-hero"><p class="eyebrow">ASCII ISOMETRIC MINI GOLF · ONLINE OR COUCH</p><h1>GOLF <em>WITH YOUR</em> ENEMIES</h1><p>Seeded nine-hole party golf with public ballots, chaos items, and server-authoritative online rooms.</p><nav><button data-home-panel="play" class="${view.panel === 'play' ? 'selected' : ''}">play</button><button data-home-panel="settings" class="${view.panel === 'settings' ? 'selected' : ''}">settings</button></nav></header>${view.panel === 'settings' ? settingsFields(view.preferences) : `<section class="home-grid"><article class="home-card panel"><p class="eyebrow">LOCAL PARTY</p><h2>couch campaign</h2><p>Pass the device between golfers. AI fills any enemy seats.</p>${configFields(view.config, 'local')}<button class="primary" data-start-local>start local game</button></article><article class="home-card panel"><p class="eyebrow">ONLINE ROOM</p><h2>host or join</h2><label>display name <input id="player-name" maxlength="16" value="${escapeHtml(view.playerName)}"></label><label>game server <input id="server-url" type="url" value="${escapeHtml(view.serverUrl)}" placeholder="ws://localhost:8787"></label>${configFields(view.config, 'online')}<button class="primary" data-create-room>create online room</button><div class="join-room"><label>room code <input id="room-code" maxlength="6" value="${escapeHtml(view.roomCode)}" placeholder="ABC123"></label><button data-join-room>join room</button></div><p class="hint">The server validates every command, owns timers and bots, and persists rooms in SQLite.</p></article></section>`}${view.notice ? `<p class="home-notice" role="status">${escapeHtml(view.notice)}</p>` : ''}</main>`;

export const renderLobbyMarkup = (room: RoomSnapshot, playerId: string | undefined, connected: boolean, notice?: string) => {
  const memberRows = room.members.map((member) => `<li><i class="${member.connected ? 'connected' : ''}"></i><strong>${escapeHtml(member.name)}</strong><span>${member.host ? 'host' : `seat ${member.slot + 1}`}</span><small>${member.connected ? 'connected' : 'reconnecting'}</small></li>`).join('');
  const host = playerId === room.hostId;
  return `<main class="lobby-shell"><header><p class="eyebrow">ONLINE CLUBHOUSE ROOM</p><h1>room <em>${escapeHtml(room.code)}</em></h1><p>Share this code with your players. The host starts when everyone is connected.</p></header><section class="lobby-card panel"><div class="room-code"><span>ROOM CODE</span><strong>${escapeHtml(room.code)}</strong><small>${connected ? 'server connected' : 'reconnecting to server'}</small></div><h2>players ${room.members.length}/${room.config.maxHumans}</h2><ol class="lobby-members">${memberRows}</ol><dl class="lobby-rules"><dt>campaign</dt><dd>${room.config.holeCount} holes · seed ${escapeHtml(room.config.seed)}</dd><dt>AI</dt><dd>${room.config.botCount} enemies · ${escapeHtml(String(room.config.botSkill))} skill</dd><dt>authority</dt><dd>server timers, bots, scores, and pause control</dd></dl>${host ? `<button class="primary" data-start-room ${room.members.some((member) => !member.connected) ? 'disabled' : ''}>start room</button>` : '<p class="hint">Waiting for the host to start the campaign.</p>'}<button data-leave-lobby>leave room</button></section>${notice ? `<p class="home-notice" role="status">${escapeHtml(notice)}</p>` : ''}</main>`;
};
