import type { GameConfig } from '../core/types';
import type { LobbyConfig, RoomSnapshot } from '../net/protocol';
import type { GamePreferences } from '../preferences';
import { escapeHtml } from './markup';

export type HomePanel = 'play' | 'settings';
export type HomeMode = 'modes' | 'local' | 'multiplayer';

export interface HomeView {
  panel: HomePanel;
  mode: HomeMode;
  config: LobbyConfig;
  preferences: GamePreferences;
  playerName: string;
  roomCode: string;
  serverUrl: string;
  connected: boolean;
  notice?: string;
}

const configFields = (config: LobbyConfig, prefix: string) => `<label>campaign seed <input id="${prefix}-seed" maxlength="32" value="${escapeHtml(config.seed)}"></label><div class="home-split"><label>holes <select id="${prefix}-holes">${[3, 6, 9, 18].map((count) => `<option value="${count}" ${config.holeCount === count ? 'selected' : ''}>${count}</option>`).join('')}</select></label><label>player seats <select id="${prefix}-seats">${Array.from({ length: 8 }, (_, index) => index + 1).map((count) => `<option value="${count}" ${config.maxHumans === count ? 'selected' : ''}>${count}</option>`).join('')}</select></label></div><div class="home-split"><label>level width <input id="${prefix}-course-width" type="number" min="14" step="1" value="${config.courseWidth}"></label><label>level height <input id="${prefix}-course-height" type="number" min="10" step="1" value="${config.courseHeight}"></label></div><p class="hint">Large courses use the follow camera. Keep online rooms within the host server's tile budget.</p><div class="home-split"><label>AI enemies <select id="${prefix}-bots">${Array.from({ length: 5 }, (_, index) => index).map((count) => `<option value="${count}" ${config.botCount === count ? 'selected' : ''}>${count}</option>`).join('')}</select></label><label>AI skill <select id="${prefix}-skill"><option value="adaptive" ${config.botSkill === 'adaptive' ? 'selected' : ''}>adaptive</option>${Array.from({ length: 10 }, (_, index) => index + 1).map((skill) => `<option value="${skill}" ${config.botSkill === skill ? 'selected' : ''}>${skill}</option>`).join('')}</select></label></div>`;

const settingsFields = (preferences: GamePreferences) => `<section class="home-settings panel"><header><p class="eyebrow">PERSISTENT CLIENT SETTINGS</p><h2>settings</h2></header><div class="settings-grid"><label class="setting-toggle"><input data-preference="reducedMotion" type="checkbox" ${preferences.reducedMotion ? 'checked' : ''}> reduced motion and flash</label><label class="setting-toggle"><input data-preference="highContrast" type="checkbox" ${preferences.highContrast ? 'checked' : ''}> high-contrast palette</label><label class="setting-toggle"><input data-preference="controllerVibration" type="checkbox" ${preferences.controllerVibration ? 'checked' : ''}> controller vibration</label><label>master volume <input data-preference-range="masterVolume" type="range" min="0" max="1" step="0.05" value="${preferences.masterVolume}"></label><label>effects volume <input data-preference-range="effectsVolume" type="range" min="0" max="1" step="0.05" value="${preferences.effectsVolume}"></label><label>controller deadzone <input data-preference-range="controllerDeadzone" type="range" min="0.05" max="0.5" step="0.01" value="${preferences.controllerDeadzone}"></label><label>controller aim sensitivity <input data-preference-range="controllerAimSensitivity" type="range" min="0.5" max="2" step="0.05" value="${preferences.controllerAimSensitivity}"></label></div><p class="hint">The standard gamepad layout uses the left stick to aim, A to shoot, B for a held item, and Menu/Start to pause.</p><button data-home-panel="play">back to clubhouse</button></section>`;

export const lobbyConfigFromGame = (config: GameConfig): LobbyConfig => ({ seed: config.seed, holeCount: config.holeCount, botCount: config.botCount, botSkill: config.botSkill, maxHumans: config.humanCount, courseWidth: config.courseWidth ?? 20, courseHeight: config.courseHeight ?? 14, skipVoting: config.skipVoting === true });

const modeCards = () => `<section class="mode-grid"><article class="mode-card panel"><span aria-hidden="true">⛳</span><p class="eyebrow">ONE SCREEN · PASS THE CLUB</p><h2>local party</h2><p>Build a couch campaign for the room, then hand the controls to the next golfer.</p><button class="primary" data-home-mode="local">play local</button></article><article class="mode-card panel"><span aria-hidden="true">⌁</span><p class="eyebrow">PRIVATE ROOM · LIVE TABLE</p><h2>multiplayer</h2><p>Create a lobby for friends or enter a room code to join the ongoing campaign.</p><button class="primary" data-home-mode="multiplayer">play online</button></article></section>`;

const localCard = (view: HomeView) => `<section class="setup-shell"><article class="home-card panel"><div class="card-back"><button data-home-mode="modes">← modes</button><p class="eyebrow">LOCAL PARTY</p></div><h2>couch campaign</h2><p>Pass the device between golfers. AI fills any enemy seats.</p>${configFields(view.config, 'local')}<button class="primary" data-start-local>start local game</button><button data-quick-start-local>quick start · no voting</button><p class="hint">Quick start randomly locks all configured holes before the first tee shot.</p></article></section>`;

const multiplayerCards = (view: HomeView) => `<section class="home-grid multiplayer-grid"><article class="home-card panel"><div class="card-back"><button data-home-mode="modes">← modes</button><p class="eyebrow">HOST A ROOM</p></div><h2>open the clubhouse</h2><p>Choose the campaign rules, create a code, then invite your players into the lobby.</p><label>display name <input id="player-name" maxlength="16" value="${escapeHtml(view.playerName)}"></label><label>game server <input id="server-url" type="url" value="${escapeHtml(view.serverUrl)}" placeholder="ws://localhost:8787"></label>${configFields(view.config, 'online')}<button class="primary" data-create-room>create room</button><button data-create-quick-room>create quick-start room · no voting</button><p class="hint">Quick start makes the server randomly lock every configured hole before the match begins.</p></article><article class="home-card panel"><p class="eyebrow">JOIN A ROOM</p><h2>enter the clubhouse</h2><p>Use the room code shared by the host. The game configuration is locked by that lobby.</p><label>display name <input id="join-player-name" maxlength="16" value="${escapeHtml(view.playerName)}"></label><label>game server <input id="join-server-url" type="url" value="${escapeHtml(view.serverUrl)}" placeholder="ws://localhost:8787"></label><label>room code <input id="room-code" maxlength="6" value="${escapeHtml(view.roomCode)}" placeholder="ABC123"></label><button class="primary" data-join-room>join room</button><p class="hint">Need a code? Ask the host. The lobby shows who is connected before the match begins.</p></article></section>`;

export const renderHomeMarkup = (view: HomeView) => {
  const playContent = view.mode === 'local' ? localCard(view) : view.mode === 'multiplayer' ? multiplayerCards(view) : modeCards();
  return `<main class="home-shell"><header class="home-hero"><p class="eyebrow">ASCII ISOMETRIC MINI GOLF · ONLINE OR COUCH</p><h1>GOLF <em>WITH YOUR</em> ENEMIES</h1><p>Seeded nine-hole party golf with public ballots, chaos items, and server-authoritative online rooms.</p><nav><button data-home-panel="play" class="${view.panel === 'play' ? 'selected' : ''}">play</button><button data-home-panel="settings" class="${view.panel === 'settings' ? 'selected' : ''}">settings</button></nav></header>${view.panel === 'settings' ? settingsFields(view.preferences) : playContent}${view.notice ? `<p class="home-notice" role="status">${escapeHtml(view.notice)}</p>` : ''}</main>`;
};

export const renderLobbyMarkup = (room: RoomSnapshot, playerId: string | undefined, connected: boolean, notice?: string) => {
  const memberRows = room.members.map((member) => `<li><i class="${member.connected ? 'connected' : ''}"></i><strong>${escapeHtml(member.name)}</strong><span>${member.host ? 'host' : `seat ${member.slot + 1}`}</span><small>${member.connected ? 'connected' : 'reconnecting'}</small></li>`).join('');
  const host = playerId === room.hostId;
  const selection = room.config.skipVoting ? 'quick start · every hole randomly locked, no voting' : 'public ballots · all holes chosen before tee-off';
  const startLabel = room.config.skipVoting ? 'start quick match' : 'start room';
  return `<main class="lobby-shell"><header><p class="eyebrow">ONLINE CLUBHOUSE ROOM</p><h1>room <em>${escapeHtml(room.code)}</em></h1><p>Share this code with your players. The host starts when everyone is connected.</p></header><section class="lobby-card panel"><div class="room-code"><span>ROOM CODE</span><strong>${escapeHtml(room.code)}</strong><small>${connected ? 'server connected' : 'reconnecting to server'}</small></div><h2>players ${room.members.length}/${room.config.maxHumans}</h2><ol class="lobby-members">${memberRows}</ol><dl class="lobby-rules"><dt>campaign</dt><dd>${room.config.holeCount} holes · ${room.config.courseWidth}×${room.config.courseHeight} tiles · seed ${escapeHtml(room.config.seed)}</dd><dt>selection</dt><dd>${selection}</dd><dt>AI</dt><dd>${room.config.botCount} enemies · ${escapeHtml(String(room.config.botSkill))} skill</dd><dt>authority</dt><dd>server timers, bots, scores, and pause control</dd></dl>${host ? `<button class="primary" data-start-room ${room.members.some((member) => !member.connected) ? 'disabled' : ''}>${startLabel}</button>` : '<p class="hint">Waiting for the host to start the campaign.</p>'}<button data-leave-lobby>leave room</button></section>${notice ? `<p class="home-notice" role="status">${escapeHtml(notice)}</p>` : ''}</main>`;
};
