import type { GameConfig } from '../core/types';
import type { LobbyConfig, RoomSnapshot } from '../net/protocol';
import type { GamePreferences } from '../preferences';
import { escapeHtml } from './markup';

export type HomePanel = 'play' | 'settings';
export type HomeMode = 'modes' | 'local' | 'multiplayer' | 'host' | 'join';

export interface HomeView {
  panel: HomePanel;
  mode: HomeMode;
  config: LobbyConfig;
  preferences: GamePreferences;
  playerName: string;
  roomCode: string;
  passphrase?: string;
  serverUrl: string;
  connected: boolean;
  notice?: string;
}

const configFields = (config: LobbyConfig, prefix: string) => `<label>campaign seed <input id="${prefix}-seed" maxlength="32" value="${escapeHtml(config.seed)}"></label><div class="home-split"><label>holes <select id="${prefix}-holes">${[3, 6, 9, 18].map((count) => `<option value="${count}" ${config.holeCount === count ? 'selected' : ''}>${count}</option>`).join('')}</select></label><label>player seats <select id="${prefix}-seats">${Array.from({ length: 8 }, (_, index) => index + 1).map((count) => `<option value="${count}" ${config.maxHumans === count ? 'selected' : ''}>${count}</option>`).join('')}</select></label></div><div class="home-split"><label>ruleset <select id="${prefix}-ruleset"><option value="party" ${config.ruleset === 'party' ? 'selected' : ''}>Party Rules</option><option value="custom" ${config.ruleset === 'custom' ? 'selected' : ''}>custom / experimental</option></select></label><label>AI enemies <select id="${prefix}-bots">${Array.from({ length: 5 }, (_, index) => index).map((count) => `<option value="${count}" ${config.botCount === count ? 'selected' : ''}>${count}</option>`).join('')}</select></label></div><div class="home-split"><label>level width <input id="${prefix}-course-width" type="number" min="14" step="1" value="${config.courseWidth}"></label><label>level height <input id="${prefix}-course-height" type="number" min="10" step="1" value="${config.courseHeight}"></label></div><p class="hint">Party Rules is the fast, readable default. Custom retains the full experimental catalogue. Large courses use the follow camera; online rooms must also stay within the host server's tile budget.</p><div class="home-split"><label>AI skill <select id="${prefix}-skill"><option value="adaptive" ${config.botSkill === 'adaptive' ? 'selected' : ''}>adaptive</option>${Array.from({ length: 10 }, (_, index) => index + 1).map((skill) => `<option value="${skill}" ${config.botSkill === skill ? 'selected' : ''}>${skill}</option>`).join('')}</select></label></div>`;

const settingsFields = (preferences: GamePreferences) => `<section class="home-settings panel"><header><p class="eyebrow">PERSISTENT CLIENT SETTINGS</p><h2>settings</h2></header><div class="settings-grid"><label class="setting-toggle"><input data-preference="reducedMotion" type="checkbox" ${preferences.reducedMotion ? 'checked' : ''}> reduced motion and flash</label><label class="setting-toggle"><input data-preference="highContrast" type="checkbox" ${preferences.highContrast ? 'checked' : ''}> high-contrast palette</label><label class="setting-toggle"><input data-preference="controllerVibration" type="checkbox" ${preferences.controllerVibration ? 'checked' : ''}> controller vibration</label><label class="setting-toggle"><input data-preference="showMerchantHoldings" type="checkbox" ${preferences.showMerchantHoldings ? 'checked' : ''}> show table cards and boons in merchant</label><label class="setting-toggle"><input data-preference="showPartyDiagnostics" type="checkbox" ${preferences.showPartyDiagnostics ? 'checked' : ''}> show local Party Rules diagnostics</label><p class="setting-note">mouse shots: left-drag to putt or right-drag to chip, then release to strike</p><label>master volume <input data-preference-range="masterVolume" type="range" min="0" max="1" step="0.05" value="${preferences.masterVolume}"></label><label>effects volume <input data-preference-range="effectsVolume" type="range" min="0" max="1" step="0.05" value="${preferences.effectsVolume}"></label><label>controller deadzone <input data-preference-range="controllerDeadzone" type="range" min="0.05" max="0.5" step="0.01" value="${preferences.controllerDeadzone}"></label><label>controller aim sensitivity <input data-preference-range="controllerAimSensitivity" type="range" min="0.5" max="2" step="0.05" value="${preferences.controllerAimSensitivity}"></label></div><section class="developer-controls"><strong>guide controls</strong><p>Replay the contextual Party Rules guide on this device.</p><button data-reset-party-guide>reset Party Rules guide</button></section><p class="hint">Controller menus: D-pad or left stick navigates, A selects, and B goes back. On the course: left stick aims, A shoots, B uses the held item, View opens game controls, and Menu/Start pauses.</p><button data-home-panel="play">back to title</button></section>`;

export const lobbyConfigFromGame = (config: GameConfig): LobbyConfig => ({ seed: config.seed, holeCount: config.holeCount, botCount: config.botCount, botSkill: config.botSkill, maxHumans: config.humanCount, courseWidth: config.courseWidth ?? 20, courseHeight: config.courseHeight ?? 14, ruleset: config.ruleset ?? 'party' });

const modeCards = () => `<section class="title-menu panel" aria-label="choose a game mode"><header><p class="eyebrow">CHOOSE A MODE</p><h2>how do you want to play?</h2><p>Play locally on one device or with friends online.</p></header><div class="mode-grid mode-grid-two"><article class="mode-card"><p class="eyebrow">LOCAL</p><h3>local play</h3><p>Play solo, add AI enemies, or pass one device between up to eight golfers.</p><button class="primary" data-home-mode="local">choose local play</button></article><article class="mode-card"><p class="eyebrow">ONLINE</p><h3>multiplayer</h3><p>Host a private room or join an existing table with a room code.</p><button class="primary" data-home-mode="multiplayer">choose multiplayer</button></article></div></section>`;

const localCard = (view: HomeView) => `<section class="setup-shell"><article class="home-card panel"><div class="card-back"><button data-home-mode="modes">← all modes</button><p class="eyebrow">LOCAL PLAY</p></div><h2>set up local play</h2><p>Choose one golfer for solo play or add seats for pass-and-play. AI enemies are optional.</p>${configFields(view.config, 'local')}<div class="home-actions"><button class="primary" data-start-local>start local game</button></div><p class="hint">Every incoming hole is seed-shuffled automatically. Random chaos is locked in before tee-off.</p></article></section>`;

const multiplayerCards = () => `<section class="title-menu panel" aria-label="choose an online game"><header><p class="eyebrow">ONLINE PLAY</p><h2>play with friends</h2><p>Start a private room or enter a code from another host.</p></header><div class="mode-grid mode-grid-two"><article class="mode-card"><p class="eyebrow">HOST</p><h3>create a room</h3><p>Choose the course rules and invite friends using a private room code.</p><button class="primary" data-home-mode="host">host a room</button></article><article class="mode-card"><p class="eyebrow">JOIN</p><h3>enter a room</h3><p>Connect to an existing game with the host's server address and room code.</p><button class="primary" data-home-mode="join">join a room</button></article></div><button class="back-button" data-home-mode="modes">← all modes</button></section>`;

const hostCard = (view: HomeView) => `<section class="setup-shell"><article class="home-card panel"><div class="card-back"><button data-home-mode="multiplayer">← online play</button><p class="eyebrow">HOST A ROOM</p></div><h2>create a private room</h2><p>Choose the campaign rules, create a code, then invite your players.</p><label>display name <input id="player-name" maxlength="16" value="${escapeHtml(view.playerName)}"></label><label>room passphrase <input id="room-passphrase" type="password" minlength="4" maxlength="128" value="${escapeHtml(view.passphrase ?? '')}" autocomplete="new-password"></label><label>game server <input id="server-url" type="url" value="${escapeHtml(view.serverUrl)}" placeholder="ws://localhost:8787"></label>${configFields(view.config, 'online')}<div class="home-actions"><button class="primary" data-create-room>create room</button></div><p class="hint">Share the room code and passphrase separately. The shuffler locks each random course before its tee-off.</p></article></section>`;

const joinCard = (view: HomeView) => `<section class="setup-shell"><article class="home-card panel"><div class="card-back"><button data-home-mode="multiplayer">← online play</button><p class="eyebrow">JOIN A ROOM</p></div><h2>join a private room</h2><p>Enter the connection details shared by the host.</p><label>display name <input id="join-player-name" maxlength="16" value="${escapeHtml(view.playerName)}"></label><label>game server <input id="join-server-url" type="url" value="${escapeHtml(view.serverUrl)}" placeholder="ws://localhost:8787"></label><label>room code <input id="room-code" maxlength="6" value="${escapeHtml(view.roomCode)}" placeholder="ABC123"></label><label>room passphrase <input id="join-room-passphrase" type="password" minlength="4" maxlength="128" value="${escapeHtml(view.passphrase ?? '')}" autocomplete="current-password"></label><div class="home-actions"><button class="primary" data-join-room>join room</button></div><p class="hint">The lobby shows who is connected before the host starts the match.</p></article></section>`;

const gearIcon = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 15.2a3.2 3.2 0 1 0 0-6.4 3.2 3.2 0 0 0 0 6.4Z"/><path d="M19.4 13.5a7.7 7.7 0 0 0 .1-1.5 7.7 7.7 0 0 0-.1-1.5l2-1.5-2-3.4-2.4 1a8 8 0 0 0-2.6-1.5L14.1 2h-4l-.4 3.1a8 8 0 0 0-2.6 1.5l-2.4-1-2 3.4 2 1.5a7.7 7.7 0 0 0-.1 1.5c0 .5 0 1 .1 1.5l-2 1.5 2 3.4 2.4-1a8 8 0 0 0 2.6 1.5l.4 3.1h4l.4-3.1a8 8 0 0 0 2.6-1.5l2.4 1 2-3.4-2.1-1.5Z"/></svg>';
const homeTitle = '<h1>GOLF <em>WITH YOUR</em> ENEMIES</h1>';

export const renderHomeMarkup = (view: HomeView) => {
  const playContent = view.mode === 'local'
    ? localCard(view)
    : view.mode === 'host'
      ? hostCard(view)
      : view.mode === 'join'
        ? joinCard(view)
        : view.mode === 'multiplayer'
          ? multiplayerCards()
          : modeCards();
  return `<main class="home-shell"><button class="home-settings-button ${view.panel === 'settings' ? 'selected' : ''}" data-home-panel="settings" aria-label="open settings" aria-pressed="${view.panel === 'settings'}" title="settings">${gearIcon}</button><header class="home-hero">${homeTitle}</header>${view.panel === 'settings' ? settingsFields(view.preferences) : playContent}${view.notice ? `<p class="home-notice" role="status">${escapeHtml(view.notice)}</p>` : ''}</main>`;
};

export const renderMatchLaunchMarkup = (_launch: { quickStart: boolean; title: string; detail: string }) => `<main class="match-loading" aria-live="polite"><span class="match-loading-ball" role="img" aria-label="loading match"></span></main>`;

export const renderQuickStartLaunchMarkup = () => renderMatchLaunchMarkup({ quickStart: false, title: 'shuffling the campaign', detail: 'Locking random courses and chaos modifiers.' });

export const renderLobbyMarkup = (room: RoomSnapshot, playerId: string | undefined, connected: boolean, notice?: string) => {
  const memberRows = room.members.map((member) => `<li><i class="${member.connected ? 'connected' : ''}"></i><strong>${escapeHtml(member.name)}</strong><span>${member.host ? 'host' : `seat ${member.slot + 1}`}</span><small>${member.connected ? 'connected' : 'reconnecting'}</small></li>`).join('');
  const host = playerId === room.hostId;
  const selection = 'seeded course shuffler · random modifiers lock before each tee-off';
  const startLabel = 'start room';
  const canStart = host && !room.members.some((member) => !member.connected);
  return `<main class="lobby-shell"><header><p class="eyebrow">ONLINE ROOM</p><h1>room <em>${escapeHtml(room.code)}</em></h1><p>Share this code with your players. The host starts when everyone is connected.</p></header><section class="lobby-card panel"><div class="room-code"><span>ROOM CODE</span><strong>${escapeHtml(room.code)}</strong><small>${connected ? 'server connected' : 'reconnecting to server'}</small></div><h2>players ${room.members.length}/${room.config.maxHumans}</h2><ol class="lobby-members">${memberRows}</ol><dl class="lobby-rules"><dt>campaign</dt><dd>${room.config.holeCount} holes · ${room.config.courseWidth}×${room.config.courseHeight} tiles · seed ${escapeHtml(room.config.seed)}</dd><dt>ruleset</dt><dd>${room.config.ruleset === 'custom' ? 'custom / experimental' : 'Party Rules'}</dd><dt>selection</dt><dd>${selection}</dd><dt>AI</dt><dd>${room.config.botCount} enemies · ${escapeHtml(String(room.config.botSkill))} skill</dd><dt>authority</dt><dd>server timers, bots, scores, and pause control</dd></dl>${host ? `<button class="primary" data-start-room ${canStart ? '' : 'disabled'}>${startLabel}</button>` : '<p class="hint">Waiting for the host to start the campaign.</p>'}<button data-leave-lobby>leave room</button></section>${notice ? `<p class="home-notice" role="status">${escapeHtml(notice)}</p>` : ''}</main>`;
};
