-- Small first-party physical cover set. Object durability comes from the
-- referenced material; these definitions only describe the object's role.
return {
  {
    id = "world_object.cover.masonry_barricade",
    display_name = "Masonry Barricade",
    material_id = "material.structure.masonry",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = false,
    render_style = "barricade",
  },
  {
    id = "world_object.cover.timber_crate",
    display_name = "Timber Crate",
    material_id = "material.structure.wood",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = true,
    render_style = "crate",
  },
  {
    id = "world_object.cover.conductive_metal_crate",
    display_name = "Conductive Metal Crate",
    material_id = "material.structure.conductive_metal",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = true,
    render_style = "metal_crate",
  },
  {
    id = "world_object.door.powered_legacy",
    display_name = "Powered Bulkhead",
    material_id = "material.structure.masonry",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = true,
    movable_by_force = false,
    interaction_role = "door",
    power_required = true,
    default_door_state = "closed",
    render_style = "powered_door",
  },
  {
    id = "world_object.power.generator_legacy",
    display_name = "Maintenance Generator",
    material_id = "material.structure.masonry",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "generator",
    render_style = "generator",
  },
  {
    id = "world_object.power.breaker_legacy",
    display_name = "Circuit Breaker",
    material_id = "material.structure.masonry",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "breaker",
    render_style = "breaker",
  },
  {
    id = "world_object.service.kiosk",
    display_name = "Service Kiosk",
    material_id = "material.structure.conductive_metal",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "service",
    render_style = "service_kiosk",
  },
  {
    id = "world_object.traversal.reinforced_barrier",
    display_name = "Reinforced Barrier",
    material_id = "material.structure.reinforced_breachable",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = true,
    movable_by_force = false,
    interaction_role = "traversal",
    render_style = "reinforced_barrier",
  },
}
