-- Small first-party physical cover set. Object durability comes from the
-- referenced material; these definitions only describe the object's role.
return {
  {
    id = "world_object.feature.old_growth_tree",
    display_name = "Old-Growth Tree",
    material_id = "material.terrain.heartwood",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = false,
    render_style = "old_growth_tree",
  },
  {
    id = "world_object.feature.fallen_log",
    display_name = "Fallen Trunk",
    material_id = "material.structure.wood",
    blocks_movement = true,
    blocks_vision = false,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = true,
    render_style = "fallen_log",
  },
  {
    id = "world_object.feature.granite_boulder",
    display_name = "Granite Boulder",
    material_id = "material.terrain.granite",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = false,
    render_style = "granite_boulder",
  },
  {
    id = "world_object.feature.stalagmite",
    display_name = "Stone Pillar",
    material_id = "material.terrain.stone",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = false,
    render_style = "stalagmite",
  },
  {
    id = "world_object.feature.rubble_pile",
    display_name = "Collapsed Rubble",
    material_id = "material.structure.masonry",
    blocks_movement = true,
    blocks_vision = false,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = false,
    render_style = "rubble_pile",
  },
  {
    id = "world_object.feature.ruined_statue",
    display_name = "Ruined Statue",
    material_id = "material.structure.masonry",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = false,
    render_style = "ruined_statue",
  },
  {
    id = "world_object.feature.machine_bank",
    display_name = "Derelict Machine Bank",
    material_id = "material.structure.industrial_bulkhead",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = true,
    movable_by_force = false,
    render_style = "machine_bank",
  },
  {
    -- This is a small, destroyable dry conductor.  It does not power logical
    -- circuits; it only participates in the existing physical conductivity
    -- query just like conductive metal flooring and water.
    id = "world_object.feature.cable_trunk",
    display_name = "Exposed Cable Trunk",
    material_id = "material.structure.conductive_metal",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    render_style = "cable_trunk",
  },
  {
    id = "world_object.cover.masonry_barricade",
    display_name = "Masonry Barricade",
    material_id = "material.structure.masonry",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = false,
    render_style = "barricade",
  },
  {
    id = "world_object.cover.timber_crate",
    display_name = "Timber Crate",
    material_id = "material.structure.wood",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = true,
    render_style = "crate",
  },
  {
    id = "world_object.cover.conductive_metal_crate",
    display_name = "Conductive Metal Crate",
    material_id = "material.structure.conductive_metal",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = true,
    render_style = "metal_crate",
  },
  {
    id = "world_object.door.powered_legacy",
    display_name = "Powered Bulkhead",
    material_id = "material.structure.masonry",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = true,
    movable_by_force = false,
    interaction_role = "door",
    power_required = true,
    default_door_state = "closed",
    render_style = "powered_door",
  },
  {
    id = "world_object.power.generator_legacy",
    display_name = "Maintenance Generator",
    material_id = "material.structure.masonry",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "generator",
    render_style = "generator",
  },
  {
    id = "world_object.power.breaker_legacy",
    display_name = "Circuit Breaker",
    material_id = "material.structure.masonry",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "breaker",
    render_style = "breaker",
  },
  {
    id = "world_object.service.kiosk",
    display_name = "Service Kiosk",
    material_id = "material.structure.conductive_metal",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "service",
    render_style = "service_kiosk",
  },
  {
    id = "world_object.traversal.reinforced_barrier",
    display_name = "Reinforced Barrier",
    material_id = "material.structure.reinforced_breachable",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = true,
    movable_by_force = false,
    interaction_role = "traversal",
    required_unlock = "unlock.traversal.reinforced_breach",
    render_style = "reinforced_barrier",
  },
  {
    id = "world_object.traversal.maintenance_hatch",
    display_name = "Sealed Maintenance Hatch",
    material_id = "material.structure.reinforced_breachable",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = true,
    movable_by_force = false,
    interaction_role = "traversal",
    required_unlock = "unlock.traversal.maintenance_override",
    render_style = "maintenance_hatch",
  },
  -- Persistent campaign topology uses ordinary, visible world objects. They
  -- are deliberately passable and interactable: changing zones is an explicit
  -- U action, not a hidden collision rule or a second navigation layer.
  {
    id = "world_object.connection.cave_mouth",
    display_name = "Cave Mouth",
    material_id = "material.terrain.stone",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "zone_connection",
    render_style = "stalagmite",
  },
  {
    id = "world_object.connection.stairs",
    display_name = "Stairs",
    material_id = "material.structure.masonry",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "zone_connection",
    render_style = "maintenance_hatch",
  },
  {
    id = "world_object.connection.ladder",
    display_name = "Ladder",
    material_id = "material.structure.wood",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "zone_connection",
    render_style = "cable_trunk",
  },
  {
    id = "world_object.connection.elevator",
    display_name = "Elevator",
    material_id = "material.structure.conductive_metal",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "zone_connection",
    render_style = "generator",
  },
  {
    id = "world_object.connection.shaft",
    display_name = "Laddered Shaft",
    material_id = "material.terrain.stone",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "zone_connection",
    render_style = "maintenance_hatch",
  },
  {
    id = "world_object.discovery.cache",
    display_name = "Discovery Cache",
    material_id = "material.structure.conductive_metal",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "discovery",
    render_style = "discovery_cache",
  },
  {
    id = "world_object.discovery.clue",
    display_name = "Access Marking",
    material_id = "material.structure.masonry",
    blocks_movement = false,
    blocks_vision = false,
    blocks_projectiles = false,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "clue",
    render_style = "discovery_clue",
  },
  {
    id = "world_object.reinforcement.nest",
    display_name = "Disturbed Nest",
    material_id = "material.structure.wood",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = false,
    movable_by_force = false,
    interaction_role = "reinforcement",
    reinforcement_source_type = "nest",
    render_style = "reinforcement_nest",
  },
  {
    id = "world_object.reinforcement.lift",
    display_name = "Maintenance Lift",
    material_id = "material.structure.masonry",
    blocks_movement = true,
    blocks_vision = true,
    blocks_projectiles = true,
    blocks_gas = true,
    movable_by_force = false,
    interaction_role = "reinforcement",
    reinforcement_source_type = "lift",
    render_style = "reinforcement_lift",
  },
}
