import type { CompanionActionCategory, CompanionRole, CompanionRoleContract } from '../types'

const contracts: Record<CompanionRole, CompanionRoleContract> = {
  guard: { version: 1, role: 'guard', description: 'Holds danger away from the courier through intercept and protection.', passiveInformation: ['visible hostile pressure near the courier'], informationBoundary: 'visible-only', legalActions: ['intercept', 'protect'], cooldownOwner: 'companion', resourceOwner: 'companion', directActions: ['intercept', 'protect'], autonomousPriorities: ['intercept attacks against the courier', 'protect the lowest-health adjacent ally'], prohibitedActions: ['reveal hidden-room locations', 'reveal unexplored tiles', 'use traversal tools', 'apply wards'] },
  scout: { version: 1, role: 'scout', description: 'Reads visible trail signs and marks discovered routes.', passiveInformation: ['visible trail signs', 'explored route branches'], informationBoundary: 'in-world-discovery', legalActions: ['observe', 'mark'], cooldownOwner: 'companion', resourceOwner: 'companion', directActions: ['observe', 'mark'], autonomousPriorities: ['inspect visible signs', 'mark already discovered hazards'], prohibitedActions: ['reveal hidden-room locations', 'intercept attacks', 'alter terrain'] },
  pathmaker: { version: 1, role: 'pathmaker', description: 'Supports terrain crossings and stable traversal.', passiveInformation: ['visible terrain blockers', 'explored traversal links'], informationBoundary: 'explored-only', legalActions: ['traverse', 'stabilizeTerrain'], cooldownOwner: 'companion', resourceOwner: 'companion', directActions: ['traverse', 'stabilizeTerrain'], autonomousPriorities: ['stabilize the active route', 'support the courier at a visible crossing'], prohibitedActions: ['reveal hidden-room locations', 'ward hazards', 'intercept attacks'] },
  ritualist: { version: 1, role: 'ritualist', description: 'Uses fictional ward rites to contain visible hazards.', passiveInformation: ['visible wards', 'explored ritual markers'], informationBoundary: 'explored-only', legalActions: ['ward', 'stabilizeHazard'], cooldownOwner: 'companion', resourceOwner: 'companion', directActions: ['ward', 'stabilizeHazard'], autonomousPriorities: ['contain visible ward hazards', 'support the courier at explored ritual markers'], prohibitedActions: ['reveal hidden-room locations', 'use physical traversal tools', 'intercept attacks'], fictionNote: 'Ritual effects are Jomon-inspired fiction, not claims about historical practice.', contentConstraint: 'TR-01' }
}
export const COMPANION_ROLE_CONTRACTS = contracts
export const companionRoleContract = (role: CompanionRole): CompanionRoleContract => ({ ...contracts[role], passiveInformation: [...contracts[role].passiveInformation], legalActions: [...contracts[role].legalActions], directActions: [...contracts[role].directActions], autonomousPriorities: [...contracts[role].autonomousPriorities], prohibitedActions: [...contracts[role].prohibitedActions] })
export const companionRoleContractErrors = (contract: CompanionRoleContract): string[] => {
  const errors: string[] = []
  if (contract.version !== 1) errors.push('unsupported version')
  if (!contract.description || !contract.passiveInformation.length || !contract.legalActions.length || !contract.directActions.length || !contract.autonomousPriorities.length || !contract.prohibitedActions.length) errors.push('incomplete role contract')
  if (contract.cooldownOwner !== 'companion' || contract.resourceOwner !== 'companion') errors.push('invalid ownership')
  if (contract.directActions.some(action => !contract.legalActions.includes(action))) errors.push('direct action is not legal')
  if (contract.role === 'ritualist' && (contract.contentConstraint !== 'TR-01' || !contract.fictionNote?.includes('Jomon-inspired fiction'))) errors.push('missing TR-01 fiction constraint')
  if (contract.role !== 'ritualist' && (contract.contentConstraint || contract.fictionNote)) errors.push('unexpected ritual constraint')
  if (contract.passiveInformation.some(info => info.includes('hidden-room location')) || contract.prohibitedActions.every(action => action !== 'reveal hidden-room locations')) errors.push('hidden-information boundary missing')
  return errors
}
export const isLegalCompanionRoleAction = (role: CompanionRole, action: CompanionActionCategory): boolean => contracts[role].legalActions.includes(action)
