-- First material foundation. Definitions are immutable shared content; World
-- owns per-cell integrity and destruction state for the active floor.
return {
  {
    id = "material.terrain.air",
    display_name = "Open Air",
    solid = false,
    blocks_movement = false,
    blocks_vision = false,
    destructible = false,
    flammable = false,
    conductive = false,
  },
  {
    id = "material.terrain.leaf_litter",
    display_name = "Dry Leaf Litter",
    solid = false,
    blocks_movement = false,
    blocks_vision = false,
    destructible = true,
    max_integrity = 3,
    destruction_material_id = "material.terrain.air",
    flammable = true,
    burn_rate = 1,
    conductive = false,
  },
  {
    id = "material.terrain.brush",
    display_name = "Dense Brush",
    solid = true,
    blocks_movement = true,
    blocks_vision = true,
    destructible = true,
    max_integrity = 2,
    destruction_material_id = "material.terrain.air",
    flammable = true,
    burn_rate = 1,
    conductive = false,
  },
  {
    id = "material.terrain.stone",
    display_name = "Stone",
    solid = true,
    blocks_movement = true,
    blocks_vision = true,
    destructible = true,
    max_integrity = 4,
    destruction_material_id = "material.terrain.air",
    flammable = false,
    conductive = false,
  },
  {
    id = "material.structure.masonry",
    display_name = "Weak Masonry",
    solid = true,
    blocks_movement = true,
    blocks_vision = true,
    destructible = true,
    max_integrity = 2,
    destruction_material_id = "material.terrain.air",
    flammable = false,
    conductive = false,
  },
  {
    id = "material.structure.wood",
    display_name = "Timber",
    solid = true,
    blocks_movement = true,
    blocks_vision = true,
    destructible = true,
    max_integrity = 4,
    destruction_material_id = "material.terrain.air",
    flammable = true,
    burn_rate = 1,
    conductive = false,
  },
  {
    id = "material.structure.conductive_metal",
    display_name = "Conductive Metal",
    solid = true,
    blocks_movement = true,
    blocks_vision = true,
    destructible = true,
    max_integrity = 5,
    destruction_material_id = "material.terrain.air",
    flammable = false,
    conductive = true,
  },
  {
    id = "material.floor.conductive_metal",
    display_name = "Conductive Deck Plating",
    solid = false,
    blocks_movement = false,
    blocks_vision = false,
    destructible = false,
    flammable = false,
    conductive = true,
  },
  {
    id = "material.structure.industrial_bulkhead",
    display_name = "Industrial Bulkhead",
    solid = true,
    blocks_movement = true,
    blocks_vision = true,
    destructible = true,
    max_integrity = 6,
    destruction_material_id = "material.terrain.air",
    flammable = false,
    conductive = false,
  },
  {
    id = "material.structure.reinforced",
    display_name = "Reinforced Boundary",
    solid = true,
    blocks_movement = true,
    blocks_vision = true,
    destructible = false,
    flammable = false,
    conductive = false,
  },
  {
    id = "material.structure.reinforced_breachable",
    display_name = "Reinforced Traverse Alloy",
    solid = true,
    blocks_movement = true,
    blocks_vision = true,
    destructible = true,
    max_integrity = 99,
    destruction_material_id = "material.terrain.air",
    flammable = false,
    conductive = false,
  },
}
