-- Legacy physical parts give the current prototype actors a real, shared
-- body model without changing their present balance.
return {
  {
    id = "component.head.legacy_optic",
    display_name = "Legacy Optic",
    compatible_slots = { "head" },
    max_integrity = 3,
    mass = 1,
    wear_per_use = 0,
    inventory = { width = 2, height = 2, rotatable = false },
    abilities = {},
  },
  {
    id = "component.core.legacy_frame",
    display_name = "Legacy Core Frame",
    compatible_slots = { "torso_core" },
    max_integrity = 5,
    mass = 4,
    wear_per_use = 0,
    inventory = { width = 2, height = 2, rotatable = false },
    abilities = {},
  },
  {
    id = "component.arm.legacy_manipulator",
    display_name = "Legacy Manipulator",
    compatible_slots = { "arm" },
    max_integrity = 3,
    mass = 2,
    wear_per_use = 0,
    inventory = { width = 1, height = 3, rotatable = true },
    abilities = {},
  },
  {
    id = "component.arm.legacy_projectile_emitter",
    display_name = "Legacy Projectile Emitter",
    compatible_slots = { "arm" },
    max_integrity = 3,
    mass = 2,
    wear_per_use = 0,
    inventory = { width = 1, height = 3, rotatable = true },
    abilities = { "ability.weapon.projectile.basic" },
  },
  {
    id = "component.arm.legacy_arcane_projector",
    display_name = "Legacy Arcane Projector",
    compatible_slots = { "arm" },
    max_integrity = 3,
    mass = 2,
    wear_per_use = 0,
    inventory = { width = 1, height = 3, rotatable = true },
    abilities = { "ability.arcane.burst" },
  },
  {
    id = "component.leg.legacy_locomotor",
    display_name = "Legacy Locomotor",
    compatible_slots = { "leg" },
    max_integrity = 3,
    mass = 2,
    wear_per_use = 0,
    inventory = { width = 1, height = 2, rotatable = true },
    abilities = { "ability.locomotion.move" },
  },
  {
    id = "component.internal.legacy_support",
    display_name = "Legacy Support System",
    compatible_slots = { "internal" },
    max_integrity = 2,
    mass = 1,
    wear_per_use = 0,
    inventory = { width = 1, height = 1, rotatable = false },
    abilities = {},
  },
  {
    id = "component.internal.legacy_volatile_charge",
    display_name = "Volatile Charge",
    compatible_slots = { "internal" },
    max_integrity = 3,
    mass = 1,
    wear_per_use = 1,
    inventory = { width = 1, height = 1, rotatable = false },
    abilities = { "ability.explosive.self_destruct" },
  },
}
