-- Legacy physical parts give the current prototype actors a real, shared
-- body model without changing their present balance.
return {
  {
    id = "component.head.legacy_optic",
    display_name = "Legacy Optic",
    compatible_slots = { "head" },
    max_integrity = 3,
    mass = 1,
    scrap_value = 2,
    wear_per_use = 0,
    inventory = { width = 2, height = 2, rotatable = false },
    abilities = {},
  },
  {
    id = "component.core.legacy_frame",
    display_name = "Legacy Core Frame",
    compatible_slots = { "torso_core" },
    max_integrity = 5,
    mass = 4,
    scrap_value = 6,
    wear_per_use = 0,
    inventory = { width = 2, height = 2, rotatable = false },
    abilities = {},
  },
  {
    id = "component.arm.legacy_manipulator",
    display_name = "Legacy Manipulator",
    compatible_slots = { "arm" },
    max_integrity = 3,
    mass = 2,
    scrap_value = 3,
    wear_per_use = 0,
    inventory = { width = 1, height = 3, rotatable = true },
    abilities = {},
  },
  {
    id = "component.arm.legacy_projectile_emitter",
    display_name = "Legacy Projectile Emitter",
    compatible_slots = { "arm" },
    max_integrity = 3,
    mass = 2,
    scrap_value = 5,
    wear_per_use = 0,
    inventory = { width = 1, height = 3, rotatable = true },
    abilities = { "ability.weapon.projectile.basic" },
  },
  {
    id = "component.arm.impact_blade",
    display_name = "Impact Blade",
    compatible_slots = { "arm" },
    max_integrity = 4,
    mass = 1,
    scrap_value = 5,
    wear_per_use = 1,
    inventory = { width = 1, height = 3, rotatable = true },
    abilities = { "ability.weapon.melee.basic" },
  },
  {
    id = "component.arm.hydraulic_ram",
    display_name = "Hydraulic Ram",
    compatible_slots = { "arm" },
    max_integrity = 6,
    mass = 5,
    scrap_value = 8,
    wear_per_use = 1,
    inventory = { width = 2, height = 3, rotatable = true },
    abilities = { "ability.weapon.melee.ram" },
  },
  {
    id = "component.arm.heavy_projectile_emitter",
    display_name = "Heavy Projectile Emitter",
    compatible_slots = { "arm" },
    max_integrity = 5,
    mass = 4,
    scrap_value = 8,
    wear_per_use = 1,
    inventory = { width = 2, height = 3, rotatable = true },
    abilities = { "ability.weapon.projectile.heavy" },
  },
  {
    id = "component.arm.legacy_arcane_projector",
    display_name = "Legacy Arcane Projector",
    compatible_slots = { "arm" },
    max_integrity = 3,
    mass = 2,
    scrap_value = 5,
    wear_per_use = 0,
    inventory = { width = 1, height = 3, rotatable = true },
    abilities = { "ability.arcane.burst" },
  },
  {
    id = "component.leg.legacy_locomotor",
    display_name = "Legacy Locomotor",
    compatible_slots = { "leg" },
    max_integrity = 3,
    mass = 2,
    scrap_value = 4,
    wear_per_use = 0,
    inventory = { width = 1, height = 2, rotatable = true },
    abilities = { "ability.locomotion.move" },
  },
  {
    id = "component.leg.lightweight_locomotor",
    display_name = "Lightweight Locomotor",
    compatible_slots = { "leg" },
    max_integrity = 2,
    mass = 1,
    scrap_value = 4,
    wear_per_use = 0,
    inventory = { width = 1, height = 2, rotatable = true },
    abilities = { "ability.locomotion.move" },
  },
  {
    id = "component.leg.reinforced_locomotor",
    display_name = "Reinforced Locomotor",
    compatible_slots = { "leg" },
    max_integrity = 6,
    mass = 4,
    scrap_value = 7,
    wear_per_use = 0,
    inventory = { width = 1, height = 3, rotatable = true },
    abilities = { "ability.locomotion.move" },
  },
  {
    id = "component.core.reinforced_frame",
    display_name = "Reinforced Core Frame",
    compatible_slots = { "torso_core" },
    max_integrity = 9,
    mass = 7,
    scrap_value = 10,
    wear_per_use = 0,
    inventory = { width = 3, height = 3, rotatable = false },
    abilities = {},
  },
  {
    id = "component.internal.legacy_support",
    display_name = "Legacy Support System",
    compatible_slots = { "internal" },
    max_integrity = 2,
    mass = 1,
    scrap_value = 2,
    wear_per_use = 0,
    inventory = { width = 1, height = 1, rotatable = false },
    abilities = {},
  },
  {
    id = "component.internal.inertial_stabilizer",
    display_name = "Inertial Stabilizer",
    compatible_slots = { "internal" },
    max_integrity = 4,
    mass = 2,
    scrap_value = 5,
    wear_per_use = 0,
    inventory = { width = 2, height = 1, rotatable = true },
    abilities = {},
  },
  {
    id = "component.internal.legacy_volatile_charge",
    display_name = "Volatile Charge",
    compatible_slots = { "internal" },
    max_integrity = 3,
    mass = 1,
    scrap_value = 3,
    wear_per_use = 1,
    inventory = { width = 1, height = 1, rotatable = false },
    abilities = { "ability.explosive.self_destruct" },
  },
  {
    id = "component.internal.legacy_shock_coil",
    display_name = "Shock Coil",
    compatible_slots = { "internal" },
    max_integrity = 5,
    mass = 1,
    scrap_value = 6,
    wear_per_use = 1,
    inventory = { width = 1, height = 1, rotatable = false },
    abilities = { "ability.electrical.discharge" },
  },
  {
    id = "component.arm.reactor_arc_blade",
    display_name = "Arc Blade",
    compatible_slots = { "arm" },
    max_integrity = 5,
    mass = 4,
    scrap_value = 10,
    wear_per_use = 1,
    inventory = { width = 2, height = 3, rotatable = true },
    abilities = { "ability.weapon.melee.basic", "ability.electrical.discharge" },
  },
  {
    id = "component.leg.shielded_locomotor",
    display_name = "Shielded Locomotor",
    compatible_slots = { "leg" },
    max_integrity = 7,
    mass = 5,
    scrap_value = 9,
    wear_per_use = 0,
    inventory = { width = 1, height = 3, rotatable = true },
    abilities = { "ability.locomotion.move" },
  },
  {
    id = "component.core.reactor_frame",
    display_name = "Reactor Frame",
    compatible_slots = { "torso_core" },
    max_integrity = 11,
    mass = 8,
    scrap_value = 13,
    wear_per_use = 0,
    inventory = { width = 3, height = 3, rotatable = false },
    abilities = {},
  },
  {
    id = "component.arm.pile_driver",
    display_name = "Pile Driver",
    compatible_slots = { "arm" },
    max_integrity = 8,
    mass = 7,
    scrap_value = 18,
    wear_per_use = 1,
    inventory = { width = 3, height = 3, rotatable = true },
    abilities = { "ability.weapon.melee.pile_driver" },
  },
  {
    id = "component.arm.siege_emitter",
    display_name = "Siege Emitter",
    compatible_slots = { "arm" },
    max_integrity = 7,
    mass = 6,
    scrap_value = 18,
    wear_per_use = 1,
    inventory = { width = 3, height = 3, rotatable = true },
    abilities = { "ability.weapon.projectile.siege" },
  },
  {
    id = "component.arm.impact_maul",
    display_name = "Impact Maul",
    compatible_slots = { "arm" },
    max_integrity = 7,
    mass = 8,
    scrap_value = 22,
    wear_per_use = 1,
    inventory = { width = 3, height = 3, rotatable = true },
    abilities = { "ability.weapon.melee.impact_maul" },
  },
  {
    id = "component.arm.barrage_emitter",
    display_name = "Barrage Emitter",
    compatible_slots = { "arm" },
    max_integrity = 6,
    mass = 6,
    scrap_value = 22,
    wear_per_use = 1,
    inventory = { width = 3, height = 3, rotatable = true },
    abilities = { "ability.weapon.projectile.barrage" },
  },
  {
    -- Apex salvage deliberately combines two already-shared body abilities
    -- instead of adding a one-off boss attack. Its mass and wear make it a
    -- flexible finale choice rather than a strict replacement for either
    -- the Pile Driver or Barrage Emitter.
    id = "component.arm.vector_lance",
    display_name = "Vector Lance",
    compatible_slots = { "arm" },
    max_integrity = 7,
    mass = 8,
    scrap_value = 26,
    wear_per_use = 1,
    inventory = { width = 3, height = 3, rotatable = true },
    abilities = { "ability.weapon.melee.basic", "ability.weapon.projectile.barrage" },
  },
}
