import type { CaddyId, ChronoCard, ContentCategory, ContentId, GadgetKind, PowerUp, RealityCard } from './types';

export interface ContentDefinition {
  id: ContentId;
  category: ContentCategory;
  icon: string;
  description: string;
  price: number;
}

const caddy = (id: CaddyId, icon: string, description: string): ContentDefinition => ({ id, category: 'caddy', icon, description, price: 6 });
const pocket = (id: PowerUp, icon: string, description: string): ContentDefinition => ({ id, category: 'pocket', icon, description, price: 4 });
const form = (id: PowerUp, icon: string, description: string): ContentDefinition => ({ id, category: 'form', icon, description, price: 4 });
const gadget = (id: GadgetKind, icon: string, description: string): ContentDefinition => ({ id, category: 'gadget', icon, description, price: 4 });
const reality = (id: RealityCard, icon: string, description: string): ContentDefinition => ({ id, category: 'reality', icon, description, price: 8 });
const chrono = (id: ChronoCard, icon: string, description: string): ContentDefinition => ({ id, category: 'chrono', icon, description, price: 10 });

export const CONTENT: readonly ContentDefinition[] = [
  caddy('heavy ball', '●', '+12% launch power and mass per stack'), caddy('ice skates', '⛸', 'slides farther on ice'), caddy('extra charge', '✚', 'refills an empty pocket after a shot'), caddy('bank shot', '↩', 'retains speed on wall rebounds'), caddy('hazard shield', '⬡', 'survives one void rebound'), caddy('chaos magnet', '🧲', 'may refill after a pocket card'), caddy('portal savvy', '◉', 'faster portal exits'), caddy('second wind', '↯', 'arms an extra putt'), caddy('scavenger', '▣', '+1 pocket capacity'), caddy('aerial ace', '⌒', 'longer chips'), caddy('cup reader', '◎', 'larger cup capture'), caddy('gadgeteer', '⚒', '+1 active gadget'),
  caddy('backboard', '▰', 'wall bounces gain speed'), caddy('pinball wizard', '✹', 'wall bounces pay cash'), caddy('rough rider', '♣', 'rough loses drag'), caddy('sand wedge', '⌁', 'sand kicks forward'), caddy('conveyor cultist', '➳', 'stronger terrain acceleration'), caddy('gatecrasher', '⊣', 'phases a closed gate'), caddy('thornmail', '✽', 'thorns kick toward the cup'), caddy('air mail', '◯', 'air rings pay cash'), caddy('shock absorber', '◌', 'resists knockback'), caddy('first responder', '✚', 'safer void recovery'), caddy('pickpocket', '▣', 'opponents picking items pays cash'), caddy('revenge club', '⚑', 'being hit empowers the next shot'), caddy('headwind', '≋', 'sinking slows opponents'), caddy('bogeyman', '☠', 'stronger while behind'), caddy('coin slot', '$', 'cash pads pay more'), caddy('broker', '¤', 'cheaper Caddies'), caddy('echo chamber', '∞', 'repeats the first trigger'), caddy('paradox partner', '⌛', 'one position rewind'), caddy('hole hunter', '◉', 'trick shots enlarge the cup'), caddy('black market caddy', '♠', 'contraband buys include a bonus card'),
  pocket('turbo', '↯', 'arm a powerful next shot'), pocket('shield', '⬡', 'survive a void fall'), pocket('bomb', '✹', 'blast a target ball'), pocket('freeze', '❄', 'skip a target turn'), pocket('swap', '⇄', 'swap balls with a target'), pocket('two putts', '2P', 'take an immediate extra putt'), pocket('cup magnet', '⊙', 'pull your ball toward the cup'), pocket('slipstream', '➳', 'reduce next-shot drag'), pocket('rebound rig', '↩', 'strengthen wall rebounds'), pocket('phase shift', '⇤', 'send a target backward'), pocket('sandbag', '▰', 'weaken a target shot'), pocket('rescue drone', '✈', 'advance along the route'), pocket('airhorn', '📣', 'force a target chip'), pocket('club flipper', '↻', 'reverse target controls'), pocket('time dilator', '⌛', 'slow a target next shot'), pocket('mugger', '♜', 'steal cash or a card'), pocket('scramble', '⇆', 'cycle every active ball'), pocket('gravity gloves', '☄', 'pull toward the cup'), pocket('bunker buster', '⛏', 'open a wall or gate'), pocket('portal remote', '◉', 'jump to a portal exit'), pocket('red tee', '⚑', 'set a recovery checkpoint'), pocket('black flag', '⚐', 'force a target to play next'), pocket('cherry bomb', '✹', 'blast all opponents'), pocket('copycat', '▣', 'copy a target pocket card'),
  form('heavy', '●', 'huge mass for one shot'), form('bouncy', '◌', 'extra lively rebounds'), form('ghost', '◐', 'phase one obstacle'), form('magnet', '🧲', 'pull toward pads'), form('ice', '❄', 'long ice slides'), form('portal', '◉', 'choose a portal exit'), form('glider', '⌒', 'long airborne time'), form('sticky', '▣', 'brake and deaden rebounds'), form('orbit', '◎', 'larger cup capture'), form('quantum', '∞', 'keep the better branch'), form('mirror', '◇', 'redirect the first rebound'), form('anvil', '⬟', 'break an obstacle'), form('vampire', '☽', 'steal cash on collision'), form('boomerang', '↶', 'return after a void fall'),
  gadget('popper pad', '↑', 'pushes crossing balls'), gadget('snare patch', '⌁', 'slows crossing balls'), gadget('blast mine', '✹', 'explodes on contact'), gadget('slick patch', '≋', 'keeps balls rolling'), gadget('sky spring', '⌃', 'launches balls airborne'), gadget('gravity well', '◉', 'pulls nearby balls'), gadget('mirror plate', '◇', 'reflects crossing balls'), gadget('toll booth', '$', 'pays its owner when crossed'), gadget('control inverter', '↻', 'reverses crossing balls controls'), gadget('portal gun', '◉', 'places a temporary portal'),
  reality('wall is cup', '▰', 'wall contact sinks the hitter'), reality('void is fairway', '░', 'fill void with fairway'), reality('fairway is ice', '❄', 'all fairway slides'), reality('gravity is sideways', '↔', 'global lateral force'), reality('cup walks', '◉', 'cup steps down the route'), reality('everybody is ghost', '◐', 'everyone phases once'), reality('two is one', '∞', 'best of two shot branches'), reality('portals are plenty', '◉', 'portals choose exits'), reality('turns are backwards', '⇤', 'reverse turn order'), reality('gates are open', '⊣', 'gates cannot close'), reality('cups are many', '$', 'cash pads capture balls'), reality('ball is cup', '●', 'ball collisions can sink'),
  chrono('undo drive', '↶', 'restore position; keep stroke'), chrono('second chance', '↺', 'restore position and stroke'), chrono('echo putt', '◌', 'repeat a prior trajectory'), chrono('future sight', '⌘', 'preview deterministic branches'), chrono('time theft', '⌛', 'take a bonus turn'), chrono('frozen frame', '❄', 'pause hazards for one shot'), chrono('parallel parking', '⇆', 'choose a legal landing branch'), chrono('grandfather clause', '⌫', 'rewind a target prior shot'),
] as const;

export const CONTENT_BY_ID: ReadonlyMap<ContentId, ContentDefinition> = new Map(CONTENT.map((definition) => [definition.id, definition]));
export const CADDIES = CONTENT.filter((definition): definition is ContentDefinition & { id: CaddyId } => definition.category === 'caddy');
export const SHOP_CATEGORIES: readonly ContentCategory[] = ['caddy', 'pocket', 'form', 'gadget', 'reality', 'chrono'];
export const definitionFor = (id: ContentId) => CONTENT_BY_ID.get(id);
