-- Declarative ability definitions. Runtime systems bind these IDs to behavior;
-- content never supplies executable callbacks.
return {
  {
    id = "ability.explosive.self_destruct",
    display_name = "Volatile Self-Destruct",
    implementation = "self_destruct",
    activation_type = "body",
  },
  {
    id = "ability.weapon.projectile.basic",
    display_name = "Basic Projectile",
    implementation = "projectile",
    activation_type = "direct",
    resource = { name = "ammo", amount = 1 },
    damage = 1,
  },
  {
    id = "ability.weapon.projectile.heavy",
    display_name = "Heavy Projectile",
    implementation = "projectile",
    activation_type = "direct",
    resource = { name = "ammo", amount = 2 },
    damage = 2,
  },
  {
    id = "ability.weapon.scatter_caster",
    display_name = "Scatter Caster",
    implementation = "scattershot",
    activation_type = "direct",
    resource = { name = "ammo", amount = 1 },
    damage = 1,
    range = 3,
    pellets = 3,
  },
  {
    id = "ability.weapon.piercing_lance",
    display_name = "Piercing Lance",
    implementation = "piercing_projectile",
    activation_type = "direct",
    resource = { name = "ammo", amount = 2 },
    damage = 2,
    range = 8,
    pierce = 1,
  },
  {
    id = "ability.weapon.melee.basic",
    display_name = "Impact Strike",
    implementation = "melee",
    activation_type = "body",
    damage = 1,
    force = 1,
  },
  {
    id = "ability.weapon.melee.ram",
    display_name = "Hydraulic Ram",
    implementation = "melee",
    activation_type = "body",
    damage = 1,
    force = 2,
  },
  {
    id = "ability.weapon.melee.pile_driver",
    display_name = "Pile Driver",
    implementation = "melee",
    activation_type = "body",
    damage = 2,
    force = 3,
  },
  {
    id = "ability.weapon.melee.impact_maul",
    display_name = "Impact Maul",
    implementation = "melee",
    activation_type = "body",
    damage = 3,
    force = 2,
  },
  {
    id = "ability.weapon.projectile.siege",
    display_name = "Siege Projectile",
    implementation = "projectile",
    activation_type = "direct",
    resource = { name = "ammo", amount = 3 },
    damage = 3,
  },
  {
    id = "ability.weapon.projectile.barrage",
    display_name = "Barrage Projectile",
    implementation = "projectile",
    activation_type = "direct",
    resource = { name = "ammo", amount = 1 },
    damage = 2,
    range = 6,
  },
  {
    id = "ability.arcane.burst",
    display_name = "Arcane Burst",
    implementation = "area_burst",
    activation_type = "body",
    range = 3,
    radius = 1,
    delay = 3,
  },
  {
    id = "ability.locomotion.move",
    display_name = "Locomotion",
    implementation = "locomotion",
    activation_type = "direct",
  },
  {
    id = "ability.electrical.discharge",
    display_name = "Electrical Discharge",
    implementation = "electrical_discharge",
    activation_type = "body",
    max_cells = 12,
    damage = 1,
  },
}
