-- Optional, persistent account discoveries. Definitions describe rewards and
-- readable access language; placement and interaction stay in shared systems.
return {
  {
    id = "discovery.forest.survey_cache",
    display_name = "Surveyor's Cache",
    description = "A weathered field recorder maps an old evacuation route.",
    allowed_biome_ids = { "biome.legacy.forest" },
    access_profile_id = "access_profile.discovery.open",
    first_data_reward = 2,
    repeat_scrap_reward = 2,
    presentation = { clue = "A faded survey mast points into the brush.", render_style = "field_cache" },
  },
  {
    id = "discovery.forest.rootline_stash",
    display_name = "Rootline Stash",
    description = "A sealed cache survived beneath a collapsed rootline.",
    allowed_biome_ids = { "biome.legacy.forest" },
    access_profile_id = "access_profile.discovery.breachable",
    first_data_reward = 2,
    repeat_scrap_reward = 2,
    presentation = { clue = "UNSTABLE MASONRY — A CACHE SIGNAL LEAKS THROUGH.", render_style = "buried_cache" },
  },
  {
    id = "discovery.cave.echo_vault",
    display_name = "Echo Vault",
    description = "A cave survey log records a route through the old strata.",
    allowed_biome_ids = { "biome.legacy.cave" },
    access_profile_id = "access_profile.discovery.breachable",
    first_data_reward = 2,
    repeat_scrap_reward = 2,
    presentation = { clue = "FRACTURED STONE — HOLLOW SPACE BEYOND.", render_style = "cave_cache" },
  },
  {
    id = "discovery.cave.conduit_survey",
    display_name = "Conduit Survey",
    description = "A corroded terminal preserves a pre-collapse power survey.",
    allowed_biome_ids = { "biome.legacy.cave" },
    access_profile_id = "access_profile.discovery.powered",
    first_data_reward = 2,
    repeat_scrap_reward = 2,
    presentation = { clue = "POWER CONDUIT CONTINUES BEYOND THE BULKHEAD.", render_style = "conduit_cache" },
  },
  {
    id = "discovery.dungeon.archivist_niche",
    display_name = "Archivist Niche",
    description = "A damaged archive terminal catalogues the district's losses.",
    allowed_biome_ids = { "biome.legacy.dungeon" },
    access_profile_id = "access_profile.discovery.powered",
    first_data_reward = 2,
    repeat_scrap_reward = 2,
    presentation = { clue = "A LIVE ACCESS CONDUIT HUMS BEYOND THIS DOOR.", render_style = "archive_cache" },
  },
  {
    id = "discovery.dungeon.sealed_ledger",
    display_name = "Sealed Ledger",
    description = "A maintenance ledger names the people who sealed this wing.",
    allowed_biome_ids = { "biome.legacy.dungeon" },
    access_profile_id = "access_profile.discovery.maintenance_hatch",
    first_data_reward = 2,
    repeat_scrap_reward = 2,
    presentation = { clue = "SEALED SERVICE HATCH — OVERRIDE PORT DETECTED.", render_style = "ledger_cache" },
  },
  {
    id = "discovery.reactor.coolant_log",
    display_name = "Coolant Log",
    description = "An emergency coolant report identifies a failed containment run.",
    allowed_biome_ids = { "biome.legacy.reactor" },
    access_profile_id = "access_profile.discovery.powered",
    first_data_reward = 2,
    repeat_scrap_reward = 2,
    presentation = { clue = "COOLANT CONTROL SIGNAL DETECTED BEYOND THE BULKHEAD.", render_style = "reactor_cache" },
  },
  {
    id = "discovery.reactor.service_blackbox",
    display_name = "Service Blackbox",
    description = "A blackbox retains the final maintenance exchange of the complex.",
    allowed_biome_ids = { "biome.legacy.reactor" },
    access_profile_id = "access_profile.discovery.maintenance_hatch",
    first_data_reward = 2,
    repeat_scrap_reward = 2,
    presentation = { clue = "SEALED SERVICE HATCH — MAINTENANCE BUS ACTIVE.", render_style = "blackbox_cache" },
  },
}
