return {
  {
    id = "enemy.legacy.bomber",
    display_name = "Bomber",
    kind = "bomber",
    elite = false,
    ammo = 0,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "left_leg", component_id = "component.leg.legacy_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.legacy_locomotor" },
      { slot_id = "internal_1", component_id = "component.internal.legacy_volatile_charge" },
    },
  },
  {
    id = "enemy.legacy.cultist",
    display_name = "Cultist",
    kind = "cultist",
    elite = false,
    ammo = 0,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "right_arm", component_id = "component.arm.legacy_arcane_projector" },
      { slot_id = "internal_1", component_id = "component.internal.legacy_shock_coil" },
      { slot_id = "left_leg", component_id = "component.leg.legacy_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.legacy_locomotor" },
    },
  },
  {
    id = "enemy.wild.ripper",
    display_name = "Ripper",
    kind = "ripper",
    elite = false,
    ammo = 0,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "left_arm", component_id = "component.arm.impact_blade" },
      { slot_id = "left_leg", component_id = "component.leg.lightweight_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.lightweight_locomotor" },
      { slot_id = "internal_1", component_id = "component.internal.legacy_support" },
    },
  },
  {
    id = "enemy.wild.skirmisher",
    display_name = "Skirmisher",
    kind = "skirmisher",
    elite = false,
    ammo = 3,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "right_arm", component_id = "component.arm.legacy_projectile_emitter" },
      { slot_id = "left_leg", component_id = "component.leg.lightweight_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.lightweight_locomotor" },
    },
  },
  {
    id = "enemy.cave.conductor",
    display_name = "Conductor",
    kind = "conductor",
    elite = false,
    ammo = 0,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "left_arm", component_id = "component.arm.impact_blade" },
      { slot_id = "left_leg", component_id = "component.leg.legacy_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.legacy_locomotor" },
      { slot_id = "internal_1", component_id = "component.internal.legacy_shock_coil" },
    },
  },
  {
    id = "enemy.dungeon.bulwark",
    display_name = "Bulwark",
    kind = "bulwark",
    elite = false,
    ammo = 0,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "torso_core", component_id = "component.core.reinforced_frame" },
      { slot_id = "right_arm", component_id = "component.arm.hydraulic_ram" },
      { slot_id = "left_leg", component_id = "component.leg.reinforced_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.reinforced_locomotor" },
      { slot_id = "internal_1", component_id = "component.internal.inertial_stabilizer" },
    },
  },
  {
    id = "enemy.dungeon.reclaimer",
    display_name = "Reclaimer",
    kind = "reclaimer",
    elite = false,
    ammo = 4,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "left_arm", component_id = "component.arm.impact_blade" },
      { slot_id = "right_arm", component_id = "component.arm.heavy_projectile_emitter" },
      { slot_id = "left_leg", component_id = "component.leg.legacy_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.legacy_locomotor" },
    },
  },
  {
    id = "enemy.elite.redundant_gunner",
    display_name = "Redundant Gunner",
    kind = "gunner_elite",
    elite = true,
    ammo = 6,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "left_arm", component_id = "component.arm.legacy_projectile_emitter" },
      { slot_id = "right_arm", component_id = "component.arm.legacy_projectile_emitter" },
      { slot_id = "left_leg", component_id = "component.leg.reinforced_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.reinforced_locomotor" },
    },
  },
  {
    id = "enemy.elite.shock_bruiser",
    display_name = "Shock Bruiser",
    kind = "shock_bruiser",
    elite = true,
    ammo = 0,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "torso_core", component_id = "component.core.reinforced_frame" },
      { slot_id = "left_arm", component_id = "component.arm.hydraulic_ram" },
      { slot_id = "left_leg", component_id = "component.leg.reinforced_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.reinforced_locomotor" },
      { slot_id = "internal_1", component_id = "component.internal.legacy_shock_coil" },
      { slot_id = "internal_2", component_id = "component.internal.inertial_stabilizer" },
    },
  },
  {
    id = "enemy.elite.volatile_heavy",
    display_name = "Volatile Heavy",
    kind = "volatile_heavy",
    elite = true,
    ammo = 0,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "torso_core", component_id = "component.core.reinforced_frame" },
      { slot_id = "right_arm", component_id = "component.arm.hydraulic_ram" },
      { slot_id = "left_leg", component_id = "component.leg.reinforced_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.reinforced_locomotor" },
      { slot_id = "internal_1", component_id = "component.internal.legacy_volatile_charge" },
      { slot_id = "internal_2", component_id = "component.internal.inertial_stabilizer" },
    },
  },
  {
    id = "enemy.reactor.arc_cutter",
    display_name = "Arc Cutter",
    kind = "arc_cutter",
    elite = false,
    ammo = 0,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "left_arm", component_id = "component.arm.reactor_arc_blade" },
      { slot_id = "left_leg", component_id = "component.leg.legacy_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.legacy_locomotor" },
      { slot_id = "internal_1", component_id = "component.internal.legacy_support" },
    },
  },
  {
    id = "enemy.reactor.maintenance_heavy",
    display_name = "Maintenance Heavy",
    kind = "maintenance_heavy",
    elite = false,
    ammo = 0,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "torso_core", component_id = "component.core.reactor_frame" },
      { slot_id = "right_arm", component_id = "component.arm.hydraulic_ram" },
      { slot_id = "left_leg", component_id = "component.leg.shielded_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.shielded_locomotor" },
      { slot_id = "internal_1", component_id = "component.internal.inertial_stabilizer" },
    },
  },
  {
    id = "enemy.reactor.suppressor",
    display_name = "Reactor Suppressor",
    kind = "reactor_suppressor",
    elite = false,
    ammo = 4,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "torso_core", component_id = "component.core.reactor_frame" },
      { slot_id = "right_arm", component_id = "component.arm.heavy_projectile_emitter" },
      { slot_id = "left_leg", component_id = "component.leg.shielded_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.shielded_locomotor" },
    },
  },
  {
    id = "enemy.elite.arc_warden",
    display_name = "Arc Warden",
    kind = "arc_warden",
    elite = true,
    ammo = 5,
    body_topology_id = "body.topology.normal",
    installed_components = {
      { slot_id = "torso_core", component_id = "component.core.reactor_frame" },
      { slot_id = "left_arm", component_id = "component.arm.reactor_arc_blade" },
      { slot_id = "right_arm", component_id = "component.arm.heavy_projectile_emitter" },
      { slot_id = "left_leg", component_id = "component.leg.shielded_locomotor" },
      { slot_id = "right_leg", component_id = "component.leg.shielded_locomotor" },
      { slot_id = "internal_1", component_id = "component.internal.legacy_shock_coil" },
    },
  },
}
