"""Input/output adapters for external mahjong formats."""

from kenjaku.io.mjai import (
    MJAI_COMPAT_MODES,
    read_mjai_events,
    to_mjai_events,
    write_mjai_events,
    write_tenhou_mjai_files,
)
from kenjaku.io.parse_cache import parse_tenhou_xml_file_cached
from kenjaku.io.replay_manifest import (
    REPLAY_INTAKE_ACCEPTED_ITEM_KIND,
    REPLAY_INTAKE_REVIEW_KIND,
    REPLAY_MANIFEST_KIND,
    REPLAY_PUBLIC_SUMMARY_KIND,
    REPLAY_SHARE_PLAN_KIND,
    ReplayIntakeDecision,
    ReplayManifestItem,
    accepted_replay_intake_items,
    build_replay_public_summary,
    build_replay_public_summary_file,
    build_replay_share_plan,
    build_replay_share_plan_file,
    format_replay_intake_review,
    format_replay_public_summary,
    format_replay_share_plan,
    review_replay_manifest,
    review_replay_manifest_file,
    write_accepted_replay_intake_jsonl,
)
from kenjaku.io.tenhou_dataset import (
    TenhouDataset,
    TenhouDatasetFile,
    TenhouParseFailure,
    iter_tenhou_xml_dataset,
    iter_tenhou_xml_dataset_files,
    parse_tenhou_xml_dataset,
    parse_tenhou_xml_paths,
    tenhou_xml_files,
)
from kenjaku.io.tenhou_meld import TenhouMeld, decode_tenhou_meld
from kenjaku.io.tenhou_tiles import tenhou_tile
from kenjaku.io.tenhou_xml import (
    TenhouAgari,
    TenhouCall,
    TenhouDiscard,
    TenhouDraw,
    TenhouEvent,
    TenhouGame,
    TenhouReach,
    TenhouRound,
    TenhouRyuukyoku,
    parse_tenhou_xml,
    parse_tenhou_xml_file,
)

__all__ = [
    "TenhouAgari",
    "TenhouCall",
    "TenhouDataset",
    "TenhouDatasetFile",
    "TenhouDiscard",
    "TenhouDraw",
    "TenhouEvent",
    "TenhouGame",
    "TenhouMeld",
    "TenhouParseFailure",
    "TenhouReach",
    "TenhouRound",
    "TenhouRyuukyoku",
    "REPLAY_INTAKE_ACCEPTED_ITEM_KIND",
    "REPLAY_INTAKE_REVIEW_KIND",
    "REPLAY_MANIFEST_KIND",
    "REPLAY_PUBLIC_SUMMARY_KIND",
    "REPLAY_SHARE_PLAN_KIND",
    "ReplayIntakeDecision",
    "ReplayManifestItem",
    "accepted_replay_intake_items",
    "build_replay_public_summary",
    "build_replay_public_summary_file",
    "build_replay_share_plan",
    "build_replay_share_plan_file",
    "decode_tenhou_meld",
    "format_replay_intake_review",
    "format_replay_public_summary",
    "format_replay_share_plan",
    "iter_tenhou_xml_dataset",
    "iter_tenhou_xml_dataset_files",
    "MJAI_COMPAT_MODES",
    "parse_tenhou_xml",
    "parse_tenhou_xml_file_cached",
    "parse_tenhou_xml_file",
    "parse_tenhou_xml_dataset",
    "parse_tenhou_xml_paths",
    "read_mjai_events",
    "review_replay_manifest",
    "review_replay_manifest_file",
    "tenhou_tile",
    "tenhou_xml_files",
    "to_mjai_events",
    "write_mjai_events",
    "write_tenhou_mjai_files",
    "write_accepted_replay_intake_jsonl",
]
