export { perform, quickCast } from './engine/input'
export { skillChoices } from './engine/progression'
export { newHero, newRun } from './engine/run'
export type { ActionResult, GameEvent, GameEventType } from './engine/shared'
export { event, hasEvent } from './engine/shared'
export { initialRoute, navigate } from './engine/routing'
export type { ScreenRoute } from './engine/routing'
export { ACTIONS, actionById } from './engine/actions'
export type { ActionDefinition, ActionShape } from './engine/actions'
export { actionCells } from './engine/geometry'
export type { GridBounds } from './engine/geometry'
export { canAffect, lineCells, resolveLineEffect } from './engine/line-effect'
export type { EffectBlocker, EffectModifier, LineEffect, TerrainModifier } from './engine/line-effect'
export { announceTelegraph, resolveTelegraphs } from './engine/telegraphs'
export type { TelegraphPlan } from './engine/telegraphs'
export { targetPreview } from './engine/targeting'
export type { TargetPreview } from './engine/targeting'
export { addCondition, conditionSpeed, hasCondition, modifyIncomingDamage, tickConditions } from './engine/conditions'
export type { ConditionTarget, ConditionTick } from './engine/conditions'
export { resolveDisplacement } from './engine/displacement'
export type { DisplacementKind, DisplacementOutcome } from './engine/displacement'
export { planEnemyIntent } from './engine/intents'
export type { EnemyIntent, EnemyPhase } from './engine/intents'
export { projectBolt } from './engine/projectiles'
export type { ProjectileCollision, ProjectilePath } from './engine/projectiles'
export { advanceGuardianPhase, arenaPhaseFor, guardianPhaseFor } from './engine/guardians'
export type { ArenaPhase, GuardianTransition } from './engine/guardians'
export { buyHubItem, createHubState, equipHubItem, hubEquipment, hubStock, hubView } from './engine/hub'
export type { HubAction, HubMutation, HubOptions, HubView } from './engine/hub'
export { AREA_ORDER, appendLegacyRecord, completeCampaignArea, initialCampaignRoute, nextArea, recordCampaignSacrifice, unlockCampaignArea, unlockNextArea } from './engine/campaign'
export { recordRescue } from './engine/rescue'
export { legacyRecordForDeath, recordDeath } from './engine/legacy'
export { AREA_GATES, gateForArea, gateModalLines, resolveAreaGate } from './engine/gates'
export type { AreaGate, GateAlternative, GateCost, GateDestination, GateResolution } from './engine/gates'
export { resolveTerrainReactions, terrainTags } from './engine/terrain'
export type { TerrainEffect, TerrainReaction, TerrainTag } from './engine/terrain'
export { actorTags, evaluateModifiers, hasTags, itemTags, queryTags, scriptTags, skillTags } from './engine/tags'
export type { ModifierEvaluation, TagModifier, TagQuery } from './engine/tags'
export { equippedEffects, evaluateEquipmentEffects } from './engine/equipment'
export type { EquipmentEffectContext, EquipmentEffectEvaluation } from './engine/equipment'
export type { EquipmentEffect, EquipmentEffectKind, EquipmentTrigger } from './effects'
export { canBreakRubble, canKnockback, strengthGuard, strengthMeleeBonus } from './engine/strength'
export { agilityEvasion, agilityMoveDistance, agilityReachBonus, agilityTelegraphAvoidance } from './engine/agility'
export { vitalityHazardReduction, vitalityRecovery, vitalityRescueRecovery, vitalityShield } from './engine/vitality'
export { hasAstralGateAccess, intellectFocusDiscount, intellectFocusRecovery, intellectScriptRange, intellectWardBonus } from './engine/intellect'
export { scriptCastProfile, scriptForItem } from './engine/scripts'
export { contextualReward, merchantStock, missingCapabilities, rewardTags } from './engine/rewards'
export type { RewardSource } from './engine/rewards'
export { grantGold, purchaseBlocker, restoreBombs, restoreRopes, spendGold, MAX_BOMBS, MAX_GOLD, MAX_ROPES } from './engine/economy'
export type { ScriptDefinition, ScriptSchool, ScriptUpgradeHook } from './content'
export { refreshFov } from './engine/visibility'
export { ENCYCLOPEDIA_SECTIONS, encyclopedia, encyclopediaEntries, hydrateEncyclopediaLegacy, observeEncyclopedia, recordEnemy, recordGate, recordTelegraph } from './engine/encyclopedia'
export { completeObjective, objectiveForFloor } from './objectives'
