import { ITEM } from './content'
import type { Biome, ItemId, Prop, PropEffectKind, PropHook, PropId, PropTag, TileKind } from './types'

export interface PropDefinition {
  id: PropId
  biome: Biome
  name: string
  description: string
  glyph: string
  color: string
  terrain: readonly TileKind[]
  tags: readonly PropTag[]
  hooks: readonly PropHook[]
  activationReward: ItemId
  effectReward: ItemId
}

const define = (definition: PropDefinition): PropDefinition => definition

export const PROP_DEFINITIONS = [
  define({ id: 'mine.oreVein', biome: 'mine', name: 'ore vein', description: 'A dense seam with a brittle mineral sheen.', glyph: 'O', color: '#d2b56f', terrain: ['floor', 'rail', 'support'], tags: ['salvage', 'force'], hooks: ['operate', 'bomb', 'force', 'throw'], activationReward: 'rock', effectReward: 'rock' }),
  define({ id: 'mine.lanternPost', biome: 'mine', name: 'lantern post', description: 'A guttering lamp marks a worked passage.', glyph: 'i', color: '#ffe18a', terrain: ['floor', 'rail'], tags: ['light', 'fire', 'hazard'], hooks: ['operate', 'fire', 'water', 'hazard'], activationReward: 'ember', effectReward: 'rock' }),
  define({ id: 'mine.brokenCart', biome: 'mine', name: 'broken cart', description: 'A splintered cart blocks a worked rail.', glyph: 'C', color: '#c9a06e', terrain: ['rail'], tags: ['route', 'force', 'salvage'], hooks: ['operate', 'bomb', 'force', 'throw'], activationReward: 'ropeBundle', effectReward: 'rock' }),
  define({ id: 'mine.warningMarker', biome: 'mine', name: 'warning marker', description: 'A painted stake warns of unstable ground.', glyph: '!', color: '#f0b56a', terrain: ['floor', 'rail', 'support'], tags: ['warning', 'hazard'], hooks: ['operate', 'fire', 'throw', 'hazard'], activationReward: 'mapScroll', effectReward: 'rock' }),
  define({ id: 'mine.skullMarker', biome: 'mine', name: 'skull marker', description: 'A miner’s warning stares from the dust.', glyph: 'x', color: '#ddd5c2', terrain: ['floor', 'rail'], tags: ['warning', 'hazard'], hooks: ['operate', 'bomb', 'throw', 'hazard'], activationReward: 'tonic', effectReward: 'rock' }),
  define({ id: 'mine.discardedParcel', biome: 'mine', name: 'discarded parcel', description: 'A sealed bundle lies under a film of ash.', glyph: '?', color: '#d9c27e', terrain: ['floor', 'support'], tags: ['cache', 'salvage'], hooks: ['operate', 'bomb', 'fire', 'throw', 'hazard'], activationReward: 'ropeBundle', effectReward: 'key' }),
  define({ id: 'wilds.mushrooms', biome: 'wilds', name: 'mushrooms', description: 'A bright cluster grows through the leaf litter.', glyph: 'm', color: '#b6df8a', terrain: ['floor', 'web'], tags: ['growth', 'root', 'fire'], hooks: ['operate', 'fire', 'water', 'root', 'throw'], activationReward: 'tonic', effectReward: 'focusTonic' }),
  define({ id: 'wilds.danglingCharm', biome: 'wilds', name: 'dangling charm', description: 'A weathered charm twists from a low branch.', glyph: 'o', color: '#ca9fe4', terrain: ['floor', 'web'], tags: ['ritual', 'root'], hooks: ['operate', 'fire', 'root', 'throw'], activationReward: 'wardScript', effectReward: 'root' }),
  define({ id: 'wilds.birdNest', biome: 'wilds', name: 'bird nest', description: 'A woven nest rustles above the path.', glyph: 'n', color: '#d8bc82', terrain: ['floor', 'web'], tags: ['growth', 'warning'], hooks: ['operate', 'fire', 'throw', 'hazard'], activationReward: 'tonic', effectReward: 'ropeBundle' }),
  define({ id: 'wilds.rootShrine', biome: 'wilds', name: 'root shrine', description: 'Roots curl around an offering stone.', glyph: '+', color: '#86c064', terrain: ['floor', 'web'], tags: ['ritual', 'root', 'growth'], hooks: ['operate', 'fire', 'water', 'root', 'force'], activationReward: 'root', effectReward: 'mend' }),
  define({ id: 'wilds.lostParcel', biome: 'wilds', name: 'lost parcel', description: 'A courier’s bundle is caught beneath ferns.', glyph: '?', color: '#dfcc91', terrain: ['floor', 'web'], tags: ['cache', 'route'], hooks: ['operate', 'fire', 'throw', 'hazard'], activationReward: 'ropeBundle', effectReward: 'tonic' }),
  define({ id: 'wilds.rootArch', biome: 'wilds', name: 'root arch', description: 'A living arch frames an overgrown trail.', glyph: 'A', color: '#71a66d', terrain: ['floor', 'web'], tags: ['route', 'growth', 'root'], hooks: ['operate', 'fire', 'root', 'force', 'throw'], activationReward: 'machete', effectReward: 'root' }),
  define({ id: 'caverns.crystalCluster', biome: 'caverns', name: 'crystal cluster', description: 'Facets catch every trace of cave light.', glyph: '*', color: '#8ce5f2', terrain: ['floor', 'darkness'], tags: ['salvage', 'force', 'light'], hooks: ['operate', 'bomb', 'force', 'throw', 'hazard'], activationReward: 'sight', effectReward: 'rock' }),
  define({ id: 'caverns.glowingFungus', biome: 'caverns', name: 'glowing fungus', description: 'Blue fungus spills a cold local glow.', glyph: 'f', color: '#8fd6c2', terrain: ['floor', 'darkness'], tags: ['light', 'growth', 'water'], hooks: ['operate', 'fire', 'water', 'root', 'throw'], activationReward: 'focusTonic', effectReward: 'tonic' }),
  define({ id: 'caverns.barnacledShrine', biome: 'caverns', name: 'barnacled shrine', description: 'A salt-crusted shrine waits beside the tide.', glyph: '+', color: '#9cc9ce', terrain: ['floor', 'water', 'darkness'], tags: ['ritual', 'water'], hooks: ['operate', 'fire', 'water', 'force', 'hazard'], activationReward: 'waterScript', effectReward: 'wardScript' }),
  define({ id: 'caverns.brokenBoat', biome: 'caverns', name: 'broken boat', description: 'A half-sunk skiff is tangled in cave reeds.', glyph: 'b', color: '#c8a879', terrain: ['floor', 'water'], tags: ['route', 'water', 'salvage'], hooks: ['operate', 'bomb', 'water', 'force', 'throw'], activationReward: 'ropeBundle', effectReward: 'rock' }),
  define({ id: 'caverns.eelTunnel', biome: 'caverns', name: 'eel tunnel', description: 'A narrow black tunnel exhales brine.', glyph: 'e', color: '#91bd9f', terrain: ['floor', 'water', 'darkness'], tags: ['route', 'water', 'hazard'], hooks: ['operate', 'bomb', 'fire', 'force', 'hazard'], activationReward: 'pull', effectReward: 'waterScript' }),
  define({ id: 'caverns.sealedParcel', biome: 'caverns', name: 'sealed parcel', description: 'Wax seals survive beneath a crust of salt.', glyph: '?', color: '#e5d6a4', terrain: ['floor', 'darkness'], tags: ['cache', 'water'], hooks: ['operate', 'bomb', 'water', 'throw', 'hazard'], activationReward: 'key', effectReward: 'focusTonic' }),
  define({ id: 'ruins.brokenStatue', biome: 'ruins', name: 'broken statue', description: 'A stone guardian has fallen across old mosaic.', glyph: 'S', color: '#b9b0c1', terrain: ['floor', 'dart'], tags: ['route', 'salvage', 'force'], hooks: ['operate', 'bomb', 'force', 'throw', 'hazard'], activationReward: 'rock', effectReward: 'tonic' }),
  define({ id: 'ruins.ritualBrazier', biome: 'ruins', name: 'ritual brazier', description: 'Cold ash waits in a ring of warding marks.', glyph: 'B', color: '#e59b64', terrain: ['floor', 'altar'], tags: ['ritual', 'fire', 'hazard'], hooks: ['operate', 'fire', 'water', 'force', 'hazard', 'ward', 'gate'], activationReward: 'ember', effectReward: 'wardScript' }),
  define({ id: 'ruins.glyphTablet', biome: 'ruins', name: 'glyph tablet', description: 'A carved tablet records a warning in stone.', glyph: 'T', color: '#c6bad6', terrain: ['floor', 'dart'], tags: ['warning', 'ritual'], hooks: ['operate', 'bomb', 'fire', 'throw', 'hazard'], activationReward: 'mapScroll', effectReward: 'sight' }),
  define({ id: 'ruins.collapsedArch', biome: 'ruins', name: 'collapsed arch', description: 'A cracked arch leans over the passage.', glyph: 'A', color: '#a89fae', terrain: ['floor', 'dart'], tags: ['route', 'salvage', 'force'], hooks: ['operate', 'bomb', 'force', 'throw', 'hazard'], activationReward: 'pickaxe', effectReward: 'rock' }),
  define({ id: 'ruins.sealedCache', biome: 'ruins', name: 'sealed cache', description: 'Bronze clasps hold a cache shut.', glyph: '?', color: '#d8b363', terrain: ['floor', 'altar'], tags: ['cache', 'ritual'], hooks: ['operate', 'bomb', 'fire', 'throw', 'hazard'], activationReward: 'key', effectReward: 'sunseal' }),
  define({ id: 'ruins.monolith', biome: 'ruins', name: 'monolith', description: 'A black monolith hums with a warded pulse.', glyph: 'M', color: '#d2a4e8', terrain: ['floor', 'altar', 'dart'], tags: ['ritual', 'force', 'hazard'], hooks: ['operate', 'bomb', 'fire', 'force', 'hazard', 'ward', 'gate'], activationReward: 'ward', effectReward: 'gate' }),
  define({ id: 'furnace.bellows', biome: 'furnace', name: 'bellows', description: 'A soot-black bellows coughs heat into the passage.', glyph: 'B', color: '#e27b55', terrain: ['floor', 'smoke'], tags: ['fire', 'smoke', 'hazard'], hooks: ['operate', 'fire', 'water', 'force', 'hazard'], activationReward: 'sootFilter', effectReward: 'firecracker' }),
  define({ id: 'furnace.liftConsole', biome: 'furnace', name: 'lift console', description: 'A chain console controls a nearby freight lift.', glyph: 'L', color: '#e9c47e', terrain: ['floor', 'lift'], tags: ['lift', 'route', 'force'], hooks: ['operate', 'force', 'throw', 'hazard'], activationReward: 'liftKey', effectReward: 'chainGuard' }),
  define({ id: 'furnace.breakwall', biome: 'furnace', name: 'breakwall rig', description: 'A scored wall waits for a controlled breach.', glyph: '#', color: '#bc8266', terrain: ['floor', 'smoke'], tags: ['route', 'force', 'hazard'], hooks: ['operate', 'bomb', 'fire', 'force', 'throw'], activationReward: 'boreGel', effectReward: 'breachCharge' }),
  define({ id: 'furnace.cinderCache', biome: 'furnace', name: 'cinder cache', description: 'A heat-sealed cache crackles beneath the ash.', glyph: '?', color: '#ef9a62', terrain: ['floor', 'smoke'], tags: ['cache', 'fire', 'salvage'], hooks: ['operate', 'bomb', 'fire', 'throw', 'hazard'], activationReward: 'cinderTonic', effectReward: 'cinderHammer' }),
  define({ id: 'furnace.smokeStack', biome: 'furnace', name: 'smoke stack', description: 'A cracked stack spills smoke into an old route.', glyph: 'S', color: '#9ca1ad', terrain: ['floor', 'smoke'], tags: ['smoke', 'route', 'hazard'], hooks: ['operate', 'fire', 'water', 'force', 'hazard'], activationReward: 'smokeMask', effectReward: 'sootFilter' }),
  define({ id: 'furnace.forgeIdol', biome: 'furnace', name: 'forge idol', description: 'A brass idol gathers heat around a broken anvil.', glyph: '+', color: '#ffd070', terrain: ['floor', 'lift'], tags: ['ritual', 'fire', 'force'], hooks: ['operate', 'bomb', 'fire', 'water', 'force', 'hazard'], activationReward: 'smokeKnife', effectReward: 'bellowsShield' }),
  define({ id: 'floodedRuins.anchorPost', biome: 'floodedRuins', name: 'anchor post', description: 'A bronze post can hold a route against the tide.', glyph: 'A', color: '#79c3cc', terrain: ['floor', 'anchor', 'current'], tags: ['anchor', 'route', 'water'], hooks: ['operate', 'water', 'force', 'throw', 'hazard'], activationReward: 'anchorSpool', effectReward: 'anchorBuckler' }),
  define({ id: 'floodedRuins.floodgate', biome: 'floodedRuins', name: 'floodgate', description: 'A crusted gate divides two old water channels.', glyph: 'G', color: '#73b8c4', terrain: ['floor', 'current', 'anchor'], tags: ['water', 'current', 'route'], hooks: ['operate', 'water', 'force', 'bomb', 'hazard'], activationReward: 'currentRune', effectReward: 'currentOrb' }),
  define({ id: 'floodedRuins.sunkenCache', biome: 'floodedRuins', name: 'sunken cache', description: 'A lacquered cache rests under clear black water.', glyph: '?', color: '#a1dfe2', terrain: ['floor', 'water', 'current'], tags: ['cache', 'water', 'salvage'], hooks: ['operate', 'water', 'bomb', 'throw', 'hazard'], activationReward: 'floodSalt', effectReward: 'anchorBlade' }),
  define({ id: 'floodedRuins.tideShrine', biome: 'floodedRuins', name: 'tide shrine', description: 'A shrine’s bowl fills and drains with the current.', glyph: '+', color: '#a4e7e9', terrain: ['floor', 'water', 'anchor'], tags: ['ritual', 'water', 'anchor'], hooks: ['operate', 'water', 'force', 'ward', 'hazard'], activationReward: 'tideCutter', effectReward: 'wingfoil' }),
  define({ id: 'floodedRuins.currentBell', biome: 'floodedRuins', name: 'current bell', description: 'A submerged bell hums whenever the water shifts.', glyph: 'b', color: '#b2e5e5', terrain: ['floor', 'current', 'anchor'], tags: ['current', 'warning', 'water'], hooks: ['operate', 'water', 'force', 'throw', 'hazard'], activationReward: 'salvageKit', effectReward: 'currentRune' }),
  define({ id: 'floodedRuins.mossBridge', biome: 'floodedRuins', name: 'moss bridge', description: 'A rope bridge sags between tide-worn columns.', glyph: '=', color: '#82b6a1', terrain: ['floor', 'anchor', 'water'], tags: ['route', 'growth', 'water'], hooks: ['operate', 'fire', 'water', 'force', 'throw', 'hazard'], activationReward: 'wingfoil', effectReward: 'anchorSpool' }),
  define({ id: 'cliffs.ropeAnchor', biome: 'cliffs', name: 'rope anchor', description: 'A weathered iron ring marks a vertical route.', glyph: '⚓', color: '#d8b66f', terrain: ['floor', 'ledge', 'rope'], tags: ['route', 'climb', 'wind'], hooks: ['operate', 'force', 'wind', 'throw'], activationReward: 'cliffSpool', effectReward: 'grappleLine' }),
  define({ id: 'cliffs.windVane', biome: 'cliffs', name: 'wind vane', description: 'A bent vane sings with the crosswind.', glyph: 'V', color: '#a8c7ff', terrain: ['floor', 'ledge'], tags: ['warning', 'wind', 'force'], hooks: ['operate', 'wind', 'force', 'hazard'], activationReward: 'skyMap', effectReward: 'thunderJar' }),
  define({ id: 'cliffs.nestCache', biome: 'cliffs', name: 'nest cache', description: 'A bundle is wedged beneath a high nest.', glyph: '?', color: '#d8d1b7', terrain: ['floor', 'ledge'], tags: ['cache', 'climb', 'salvage'], hooks: ['operate', 'wind', 'throw', 'hazard'], activationReward: 'cliffSpool', effectReward: 'windhook' }),
  define({ id: 'cliffs.skyShrine', biome: 'cliffs', name: 'sky shrine', description: 'Stone ribbons point toward the open sky.', glyph: '+', color: '#c4e5f2', terrain: ['floor', 'ledge'], tags: ['ritual', 'wind', 'climb'], hooks: ['operate', 'wind', 'force', 'ward', 'hazard'], activationReward: 'gust', effectReward: 'galeMantle' }),
  define({ id: 'cliffs.crackedLedge', biome: 'cliffs', name: 'cracked ledge', description: 'A ledge flexes over a deep drop.', glyph: '=', color: '#8398b4', terrain: ['floor', 'ledge'], tags: ['route', 'climb', 'hazard'], hooks: ['operate', 'force', 'throw', 'hazard'], activationReward: 'ropeBundle', effectReward: 'thunderJar' }),
  define({ id: 'cliffs.signalFire', biome: 'cliffs', name: 'signal fire', description: 'Cold charcoal waits in a storm-bent brazier.', glyph: 'i', color: '#c9e7f7', terrain: ['floor', 'ledge'], tags: ['light', 'wind', 'fire'], hooks: ['operate', 'fire', 'wind', 'hazard'], activationReward: 'ember', effectReward: 'skyMap' }),
  define({ id: 'burial.cairnGate', biome: 'burial', name: 'cairn gate', description: 'Stacked stones seal a narrow barrow path.', glyph: 'A', color: '#b9aa94', terrain: ['floor', 'cairn'], tags: ['route', 'grave', 'force'], hooks: ['operate', 'force', 'bomb', 'spirit'], activationReward: 'tombKey', effectReward: 'graveSickle' }),
  define({ id: 'burial.funeralLantern', biome: 'burial', name: 'funeral lantern', description: 'A violet flame burns without oil.', glyph: 'i', color: '#c9a6db', terrain: ['floor', 'graveSoil', 'spiritPath'], tags: ['light', 'spirit', 'ritual'], hooks: ['operate', 'spirit', 'ward', 'hazard'], activationReward: 'ancestorToken', effectReward: 'mourningBell' }),
  define({ id: 'burial.ossuaryCache', biome: 'burial', name: 'ossuary cache', description: 'Bone clasps protect a sealed offering.', glyph: '?', color: '#d9d3c5', terrain: ['floor', 'ossuary'], tags: ['cache', 'grave', 'salvage'], hooks: ['operate', 'spirit', 'bomb', 'throw'], activationReward: 'graveSalt', effectReward: 'tombKey' }),
  define({ id: 'burial.graveBloom', biome: 'burial', name: 'grave bloom', description: 'Pale flowers thread through old soil.', glyph: '*', color: '#d8c1e7', terrain: ['floor', 'graveSoil'], tags: ['growth', 'grave', 'spirit'], hooks: ['operate', 'spirit', 'root', 'hazard'], activationReward: 'graveSalt', effectReward: 'ancestorToken' }),
  define({ id: 'burial.ancestorStone', biome: 'burial', name: 'ancestor stone', description: 'A carved name waits beneath soft lichen.', glyph: 'S', color: '#bba9d0', terrain: ['floor', 'cairn', 'spiritPath'], tags: ['ritual', 'spirit', 'grave'], hooks: ['operate', 'spirit', 'ward', 'force'], activationReward: 'mourningBell', effectReward: 'ward' }),
  define({ id: 'burial.sealedTomb', biome: 'burial', name: 'sealed tomb', description: 'Bronze seals bind a tomb door shut.', glyph: 'T', color: '#cba96f', terrain: ['floor', 'ossuary'], tags: ['cache', 'grave', 'hazard'], hooks: ['operate', 'bomb', 'spirit', 'throw'], activationReward: 'tombKey', effectReward: 'graveSickle' }),
  define({ id: 'saltFlats.mirageCairn', biome: 'saltFlats', name: 'mirage cairn', description: 'A salt cairn shifts whenever you look away.', glyph: '△', color: '#f1df9a', terrain: ['floor', 'saltMirror'], tags: ['salt', 'mirror', 'warning'], hooks: ['operate', 'force', 'throw', 'hazard'], activationReward: 'mapScroll', effectReward: 'focusTonic' }),
  define({ id: 'saltFlats.sunMirror', biome: 'saltFlats', name: 'sun mirror', description: 'A polished plate throws hard light across the flats.', glyph: '◇', color: '#fff1ae', terrain: ['floor', 'saltMirror'], tags: ['salt', 'mirror', 'light'], hooks: ['operate', 'fire', 'force', 'hazard'], activationReward: 'sight', effectReward: 'sunblade' }),
  define({ id: 'saltFlats.brineWell', biome: 'saltFlats', name: 'brine well', description: 'Black brine wells beneath a crust of white salt.', glyph: '≈', color: '#76bbc4', terrain: ['floor', 'brine'], tags: ['brine', 'salt', 'hazard'], hooks: ['operate', 'water', 'force', 'hazard'], activationReward: 'focusTonic', effectReward: 'tonic' }),
  define({ id: 'saltFlats.caravanHusk', biome: 'saltFlats', name: 'caravan husk', description: 'A stripped courier cart points toward a false horizon.', glyph: 'C', color: '#c7a76f', terrain: ['floor', 'crumble'], tags: ['route', 'salt', 'salvage'], hooks: ['operate', 'bomb', 'force', 'throw'], activationReward: 'ropeBundle', effectReward: 'bridgeKit' }),
  define({ id: 'saltFlats.glassMarker', biome: 'saltFlats', name: 'glass marker', description: 'A sun-bleached sign lists routes that no longer exist.', glyph: '!', color: '#d5eff0', terrain: ['floor', 'saltMirror'], tags: ['warning', 'mirror', 'salt'], hooks: ['operate', 'fire', 'throw', 'hazard'], activationReward: 'mapScroll', effectReward: 'blink' }),
  define({ id: 'saltFlats.whiteCache', biome: 'saltFlats', name: 'white cache', description: 'A waxed parcel lies buried in hard salt.', glyph: '?', color: '#f3ebc2', terrain: ['floor', 'saltMirror'], tags: ['cache', 'salt', 'salvage'], hooks: ['operate', 'bomb', 'fire', 'throw', 'hazard'], activationReward: 'tonic', effectReward: 'fireJar' }),
  define({ id: 'frostReliquary.duelBell', biome: 'frostReliquary', name: 'wind shelter', description: 'A low snow wall breaks the whiteout and marks a safe rest.', glyph: '∩', color: '#d8f1ff', terrain: ['floor'], tags: ['frost', 'route', 'warning'], hooks: ['operate', 'force', 'ward', 'hazard'], activationReward: 'ward', effectReward: 'focusTonic' }),
  define({ id: 'frostReliquary.rimeSarcophagus', biome: 'frostReliquary', name: 'trail marker', description: 'Blue pennants point from the shore toward the next shelter.', glyph: '!', color: '#b9dbea', terrain: ['floor', 'ice'], tags: ['frost', 'ice', 'warning'], hooks: ['operate', 'bomb', 'force', 'throw'], activationReward: 'mapScroll', effectReward: 'sight' }),
  define({ id: 'frostReliquary.iceForge', biome: 'frostReliquary', name: 'ice bridge', description: 'A lashed bridge spans a crack where the lake ice has pulled apart.', glyph: '=', color: '#aee6f4', terrain: ['floor', 'ice'], tags: ['frost', 'ice', 'route'], hooks: ['operate', 'fire', 'force', 'hazard'], activationReward: 'bridgeKit', effectReward: 'portableWinch' }),
  define({ id: 'frostReliquary.frozenCache', biome: 'frostReliquary', name: 'broken sled', description: 'A splintered sled offers a risky cache beside the pressure crack.', glyph: 's', color: '#e2f6ff', terrain: ['floor', 'frostRime'], tags: ['cache', 'frost', 'ice'], hooks: ['operate', 'fire', 'bomb', 'throw'], activationReward: 'tonic', effectReward: 'grappleLine' }),
  define({ id: 'frostReliquary.reliquaryWard', biome: 'frostReliquary', name: 'reliquary ward', description: 'A cold wardstone preserves a narrow dueling ground.', glyph: '◇', color: '#d2c7ff', terrain: ['floor', 'ice'], tags: ['frost', 'duel', 'ward'], hooks: ['operate', 'ward', 'force', 'hazard'], activationReward: 'wardScript', effectReward: 'mend' }),
  define({ id: 'frostReliquary.thawValve', biome: 'frostReliquary', name: 'thaw valve', description: 'A brass valve can flood the reliquary with freezing melt.', glyph: 'V', color: '#d9bf83', terrain: ['floor', 'frostRime'], tags: ['frost', 'ice', 'route'], hooks: ['operate', 'fire', 'water', 'force', 'hazard'], activationReward: 'portableWinch', effectReward: 'bridgeKit' })
] as const satisfies readonly PropDefinition[]

export const PROP_IDS = PROP_DEFINITIONS.map(definition => definition.id) as readonly PropId[]
const definitions = new Map<PropId, PropDefinition>(PROP_DEFINITIONS.map(definition => [definition.id, definition]))

export const propDefinition = (id: PropId): PropDefinition => {
  const definition = definitions.get(id)
  if (!definition) throw new Error(`missing prop definition: ${id}`)
  return definition
}

export const propDefinitionsFor = (biome: Biome): readonly PropDefinition[] => PROP_DEFINITIONS.filter(definition => definition.biome === biome)
export const propAt = (props: readonly Prop[], x: number, y: number): Prop | undefined => props.find(prop => prop.x === x && prop.y === y && prop.state !== 'destroyed')
export const isBlockingProp = (prop: Prop | undefined): boolean => (prop?.kind === 'mine.brokenCart' && prop.state !== 'destroyed') || (prop?.kind === 'wilds.rootArch' && prop.state !== 'activated' && prop.state !== 'destroyed') || (prop?.kind === 'caverns.brokenBoat' && prop.state !== 'activated' && prop.state !== 'destroyed') || (prop?.kind === 'caverns.eelTunnel' && prop.state === 'activated') || (prop?.kind === 'ruins.collapsedArch' && prop.state !== 'activated' && prop.state !== 'destroyed')
export const isSightBlockingProp = (prop: Prop | undefined): boolean => (prop?.kind === 'caverns.crystalCluster' && prop.state !== 'activated' && prop.state !== 'destroyed') || (prop?.kind === 'ruins.brokenStatue' && prop.state === 'activated')
export const isLineBlockingProp = (prop: Prop | undefined): boolean => isBlockingProp(prop) || isSightBlockingProp(prop)
export const linePropBlocker = (prop: Prop | undefined): 'cart' | 'crystal' | 'cover' | undefined => isBlockingProp(prop) ? 'cart' : prop?.kind === 'caverns.crystalCluster' && isSightBlockingProp(prop) ? 'crystal' : isSightBlockingProp(prop) ? 'cover' : undefined
export const propEffects = (hooks: readonly PropHook[]): PropEffectKind[] => hooks.filter((hook): hook is PropEffectKind => hook !== 'operate')

export const validatePropDefinitions = (): string[] => {
  const errors: string[] = []
  if (PROP_DEFINITIONS.length !== 60) errors.push(`expected 60 prop definitions, found ${PROP_DEFINITIONS.length}`)
  const ids = new Set<string>()
  for (const definition of PROP_DEFINITIONS) {
    if (ids.has(definition.id)) errors.push(`duplicate prop definition: ${definition.id}`)
    ids.add(definition.id)
    if (!definition.tags.length) errors.push(`missing tags: ${definition.id}`)
    if (!definition.hooks.includes('operate') || !propEffects(definition.hooks).length) errors.push(`incomplete hooks: ${definition.id}`)
    if (!ITEM[definition.activationReward] || !ITEM[definition.effectReward]) errors.push(`unknown reward: ${definition.id}`)
  }
  for (const biome of ['mine', 'wilds', 'caverns', 'ruins', 'furnace', 'floodedRuins', 'cliffs', 'burial', 'saltFlats', 'frostReliquary'] as const) if (propDefinitionsFor(biome).length !== 6) errors.push(`expected 6 ${biome} props`)
  return errors
}
