-- Standalone mouse-driven mapper for ROAG's Kenney 1-Bit sprite sheet.
-- Launch from the repository root with: love sprite_editor

local COLUMNS, ROWS, SOURCE_TILE_SIZE = 49, 22, 16
local JSON_FILE = "mappings.json"

local DEFAULT_MAPPINGS = {
  player={25,1}, target={38,3}, ammo={23,5}, torch={20,7}, door={22,1},
  bullet={34,3}, bomb={38,6}, flare={23,6}, necromancer={27,10}, wolf={31,9},
  bomber={20,9}, cultist={28,10}, boss={30,2},
}
local ROLES = {
  {key="player", label="Player"}, {key="target", label="Target"},
  {key="ammo", label="Ammo"}, {key="torch", label="Torch"},
  {key="door", label="Exit door"}, {key="bullet", label="Bullet"},
  {key="bomb", label="Bomb"}, {key="flare", label="Flare"},
  {key="wolf", label="Wolf"}, {key="bomber", label="Bomber"},
  {key="necromancer", label="Necromancer"}, {key="cultist", label="Cultist"},
  {key="boss", label="Boss"},
}

local mappings, selected_role, sheet, quads, dirty, status

local function clone_mappings(source)
  local result={}
  for key,tile in pairs(source) do result[key]={tile[1],tile[2]} end
  return result
end

local function set_color(r,g,b,a) love.graphics.setColor(r,g,b,a or 1) end
local function draw_text(value,x,y,size,r,g,b)
  set_color(r or 1,g or 1,b or 1)
  love.graphics.print(value,x,y,0,size or 1)
end

local function editor_layout()
  local width,height=love.graphics.getDimensions()
  local scale=math.min(1,math.max(.5,math.min((width-450)/(COLUMNS*SOURCE_TILE_SIZE),(height-112)/(ROWS*SOURCE_TILE_SIZE))))
  local tile_size=SOURCE_TILE_SIZE*scale
  local sheet_width,sheet_height=COLUMNS*tile_size,ROWS*tile_size
  return {
    width=width, height=height, tile_size=tile_size,
    sheet_x=width-sheet_width-28, sheet_y=86,
    sheet_width=sheet_width, sheet_height=sheet_height,
    role_x=24, role_y=154, role_width=380, role_height=30,
    button_y=height-76,
  }
end

local function selected()
  return ROLES[selected_role]
end

local function valid_tile(column,row)
  return column>=1 and column<=COLUMNS and row>=1 and row<=ROWS
end

local function serialize_json()
  local lines={"{", "  \"version\": 1,", "  \"sprites\": {"}
  for index,role in ipairs(ROLES) do
    local tile=mappings[role.key]
    local suffix=index==#ROLES and "" or ","
    lines[#lines+1]=string.format("    \"%s\": {\"column\": %d, \"row\": %d}%s",role.key,tile[1],tile[2],suffix)
  end
  lines[#lines+1]="  }"
  lines[#lines+1]="}"
  return table.concat(lines,"\n").."\n"
end

local function deserialize_json(contents)
  local loaded,count={},0
  for key,column,row in contents:gmatch('\"([%w_]+)\"%s*:%s*{%s*\"column\"%s*:%s*(%d+)%s*,%s*\"row\"%s*:%s*(%d+)%s*}') do
    column,row=tonumber(column),tonumber(row)
    if DEFAULT_MAPPINGS[key] and valid_tile(column,row) then
      loaded[key]={column,row}
      count=count+1
    end
  end
  if count==0 then return nil,"No valid ROAG mappings were found in "..JSON_FILE.."." end
  for key,default in pairs(DEFAULT_MAPPINGS) do
    mappings[key]=loaded[key] or {default[1],default[2]}
  end
  return true
end

local function save_json()
  local ok,err=love.filesystem.write(JSON_FILE,serialize_json())
  if ok then
    dirty=false
    status="Saved "..JSON_FILE.." in "..love.filesystem.getSaveDirectory()
  else
    status="Could not save: "..tostring(err)
  end
end

local function load_json()
  local contents,err=love.filesystem.read(JSON_FILE)
  if not contents then
    status="No saved JSON yet. Choose tiles, then click SAVE JSON."
    return
  end
  local ok,message=deserialize_json(contents)
  if ok then
    dirty=false
    status="Loaded "..JSON_FILE.." from "..love.filesystem.getSaveDirectory()
  else
    status=message or tostring(err)
  end
end

local function serialize_lua()
  local lines={"-- Generated by ROAG Sprite Editor.", "return {"}
  for _,role in ipairs(ROLES) do
    local tile=mappings[role.key]
    lines[#lines+1]=string.format("  %s = {%d, %d},",role.key,tile[1],tile[2])
  end
  lines[#lines+1]="}"
  return table.concat(lines,"\n").."\n"
end

local function copy_lua()
  love.system.setClipboardText(serialize_lua())
  status="Copied a replacement sprite_map.lua table to the clipboard."
end

local function reset_all()
  mappings=clone_mappings(DEFAULT_MAPPINGS)
  dirty=true
  status="Restored the built-in mapping. Click SAVE JSON to keep it."
end

local function button_layout(layout)
  local width,gap=92,8
  return {
    {label="SAVE JSON", x=24, y=layout.button_y, width=width, action=save_json},
    {label="LOAD JSON", x=24+(width+gap), y=layout.button_y, width=width, action=load_json},
    {label="COPY LUA", x=24+(width+gap)*2, y=layout.button_y, width=width, action=copy_lua},
    {label="RESET", x=24+(width+gap)*3, y=layout.button_y, width=width, action=reset_all},
  }
end

local function point_in_rect(x,y,rect)
  return x>=rect.x and x<=rect.x+rect.width and y>=rect.y and y<=rect.y+(rect.height or 34)
end

function love.load()
  love.graphics.setDefaultFilter("nearest","nearest")
  love.graphics.setNewFont(16)

  sheet=love.graphics.newImage("colored_packed.png")
  quads={}
  for column=1,COLUMNS do
    for row=1,ROWS do
      quads[column..":"..row]=love.graphics.newQuad((column-1)*SOURCE_TILE_SIZE,(row-1)*SOURCE_TILE_SIZE,SOURCE_TILE_SIZE,SOURCE_TILE_SIZE,sheet)
    end
  end

  mappings=clone_mappings(DEFAULT_MAPPINGS)
  selected_role=1
  dirty=false
  status="Click a role, then click a tile. SAVE JSON persists the mapping locally."
  if love.filesystem.getInfo(JSON_FILE) then load_json() end
end

function love.draw()
  local layout=editor_layout()
  love.graphics.clear(.025,.035,.055)

  draw_text("ROAG SPRITE EDITOR",24,24,2,.7,.9,1)
  draw_text("Click a role, then click a sprite-sheet tile.",24,70,1,.78,.84,.94)
  draw_text("Local JSON: "..love.filesystem.getSaveDirectory().."/"..JSON_FILE,24,94,.7,.65,.72,.84)
  draw_text("Selected: "..selected().label.."  →  ["..mappings[selected().key][1]..", "..mappings[selected().key][2].."]"..(dirty and "  UNSAVED" or ""),24,120,1,.95,.85,.3)

  for index,role in ipairs(ROLES) do
    local y=layout.role_y+(index-1)*layout.role_height
    if index==selected_role then set_color(.13,.22,.3);love.graphics.rectangle("fill",layout.role_x,y,layout.role_width,layout.role_height-3) end
    local tile=mappings[role.key]
    love.graphics.draw(sheet,quads[tile[1]..":"..tile[2]],layout.role_x+6,y+3,0,1.5,1.5)
    draw_text(role.label.."  ["..tile[1]..", "..tile[2].."]",layout.role_x+36,y+6,.9,index==selected_role and .95 or .78,index==selected_role and .85 or .83,index==selected_role and .3 or .9)
  end

  set_color(.08,.1,.14);love.graphics.rectangle("fill",layout.sheet_x-4,layout.sheet_y-4,layout.sheet_width+8,layout.sheet_height+8)
  love.graphics.draw(sheet,layout.sheet_x,layout.sheet_y,0,layout.tile_size/SOURCE_TILE_SIZE,layout.tile_size/SOURCE_TILE_SIZE)

  local function outline(column,row,r,g,b,width)
    set_color(r,g,b);love.graphics.setLineWidth(width)
    love.graphics.rectangle("line",layout.sheet_x+(column-1)*layout.tile_size,layout.sheet_y+(row-1)*layout.tile_size,layout.tile_size,layout.tile_size)
  end
  local assigned=mappings[selected().key]
  outline(assigned[1],assigned[2],.15,.9,1,2)
  local mouse_x,mouse_y=love.mouse.getPosition()
  if mouse_x>=layout.sheet_x and mouse_x<layout.sheet_x+layout.sheet_width and mouse_y>=layout.sheet_y and mouse_y<layout.sheet_y+layout.sheet_height then
    local column=math.floor((mouse_x-layout.sheet_x)/layout.tile_size)+1
    local row=math.floor((mouse_y-layout.sheet_y)/layout.tile_size)+1
    outline(column,row,1,.85,.2,3)
    draw_text("HOVER: ["..column..", "..row.."]",layout.sheet_x,layout.sheet_y+layout.sheet_height+12,.75,.95,.85,.3)
  end
  love.graphics.setLineWidth(1)

  for _,button in ipairs(button_layout(layout)) do
    set_color(.13,.22,.3);love.graphics.rectangle("fill",button.x,button.y,button.width,34)
    draw_text(button.label,button.x+9,button.y+10,.72,.9,.93,1)
  end
  draw_text(status,24,layout.height-30,.68,.78,.84,.94)
end

function love.mousepressed(x,y,button)
  if button~=1 then return end
  local layout=editor_layout()
  for _,control in ipairs(button_layout(layout)) do
    if point_in_rect(x,y,control) then control.action();return end
  end
  for index in ipairs(ROLES) do
    local row={x=layout.role_x,y=layout.role_y+(index-1)*layout.role_height,width=layout.role_width,height=layout.role_height-3}
    if point_in_rect(x,y,row) then selected_role=index;return end
  end
  if x>=layout.sheet_x and x<layout.sheet_x+layout.sheet_width and y>=layout.sheet_y and y<layout.sheet_y+layout.sheet_height then
    local column=math.floor((x-layout.sheet_x)/layout.tile_size)+1
    local row=math.floor((y-layout.sheet_y)/layout.tile_size)+1
    mappings[selected().key]={column,row}
    dirty=true
    status=selected().label.." is now ["..column..", "..row.."]. Click SAVE JSON to keep it."
  end
end

function love.keypressed(key)
  if key=="escape" then love.event.quit()
  elseif key=="s" and (love.keyboard.isDown("lctrl") or love.keyboard.isDown("rctrl")) then save_json()
  elseif key=="l" and (love.keyboard.isDown("lctrl") or love.keyboard.isDown("rctrl")) then load_json()
  end
end
